### ISSUE TITLE
Emitter assembler recipes

### ISSUE THREAD

**Issue by schliip** [Gregicality/gregicality#100]
# Expected Behavior
Emitter recipes in the Assembler should be the same material cost as Crafting Table recipes or cheaper
# Current Behavior
Emitters cost 576mb of molten metal, while crafting takes 4 rods, or 288mb
![image](https://user-images.githubusercontent.com/34576051/87238368-b88b3980-c3cf-11ea-84d5-3ecde7e11e28.png)
![image](https://user-images.githubusercontent.com/34576051/87238433-757d9600-c3d0-11ea-98d5-a24bedbdab09.png)

# Possible Solution
Change emitter recipes in assembler to require 288mb metal

**Comment by huneau** [comment]
fixed in 0.20.4, all components have simple recipe in assembler
