### ISSUE TITLE
Crystal Circuit mistake

### ISSUE THREAD

**Issue by Shattered2909** [Gregicality/gregicality#103]
![2020-07-14_09 41 50](https://user-images.githubusercontent.com/35029480/87398579-593b4e00-c5b6-11ea-9a94-1d7d8661b98b.png)
![2020-07-14_09 41 54](https://user-images.githubusercontent.com/35029480/87398585-5c363e80-c5b6-11ea-8c87-0cdcd187d821.png)

See here, making the Crystal CPU takes an LuV Engraver but the Engraved Crystal Chip (from EBF) is enough to make the Circuit. Should be changed to only require an IV Engraver, Crystal SoC requires an LuV Engraver and that is fine (except that the Engraver does not exist atm) so the SoC is required to make cheap Crystalprocessors.

**Comment by huneau** [comment]
have you disable high tier engraver ?

**Comment by Shattered2909** [comment]
Yes. The Multi Use Machine can do engraving but in my opinion there should be a Multiblock Engraver.

**Comment by TechLord22** [comment]
This has been fixed for a long time.
