### ISSUE TITLE
Disabling Double Ingots in the Config does not actually disable them

### ISSUE THREAD

**Issue by Shattered2909** [Gregicality/gregicality#105]
Yes.

**Comment by hjae78** [comment]
Looks like the double ingot prefix is registered before the config values are read for some reason.

**Comment by Shattered2909** [comment]
I wonder if there is a similar problem with the Bending Cylinder/Curved Plates

**Comment by hjae78** [comment]
Ye there was, the config options didn't do anything. I fixed it in my pr
