### ISSUE TITLE
Basic Electronic Circuits require too many MV machines

### ISSUE THREAD

**Issue by schliip** [Gregicality/gregicality#107]
(Gregicality Skyblock Edition)
## **Basic Electronic Circuits** require:
**Capacitors**, which require **Polyethylene** (MV _Chemical Reactor_, MV _Distillery_), and MV _Assembling Machine_ 
**Central Processing Unit**, which require MV _Cutting Saw_, MV _Precision Laser Engraver_

I think that far too many MV machines are required to be crafted with only **Primitive Assembly** before unlocking better circuits.

For other circuit tiers, the _Circuit Assembling Machine_ is the only machine for which the highest available circuits are needed, to unlock that tier

## Propose:
Remove **Capacitor** from **Basic Electronic Circuit** recipe

**Comment by Shattered2909** [comment]
No, that is how it's intended, if you look at other tiers of Circuits that is always how it works. If you want to make Nano Circuits (which are HV to LuV) you need plenty of EV machines/ingredients. That is just how Gregicality Circuits work, you start 1 tier below and climb up to 2 higher. Also removing Capacitors from Circuits would make it a lot less logical.

**Comment by huneau** [comment]
@schliip shaterred is right. I copy the omnifactory progression

**Comment by schliip** [comment]
@huneau Omnifactory has a recipe for 4x **Capacitor** that uses 4x **Tin Alloy Foil**, 2x **Rubber Sheet**, 2x **Fine Silver Wire**, so the requirements to produce **Electronic Circuit** are significantly easier. 

![image](https://user-images.githubusercontent.com/34576051/87587492-27a6ad80-c6b0-11ea-9aa3-9644a42f623e.png)

Please consider adding a recipe like this to make them available before **Polyethylene**, as Polyethylene also unlocks **Refined SMD** components, making the basic recipe immediately obsolete.
