### ISSUE TITLE
Superconductor inconsistency and UV/MAX tier inconsistency

### ISSUE THREAD

**Issue by Shattered2909** [Gregicality/gregicality#108]
What is up with the different amounts of Amps that Superconductors can hold?
Normal GT one takes 4 Amps per Wire
Gregicality ones:
MV - 2 Amps
HV - 2 Amps
EV - 4 Amps
IV - 4 Amps
LuV - 8 Amps
ZPM - 8 Amps
UV - nonexistent, why?

I think LV should have Superconductors as well, it is one of the tiers where power loss really matters, I added Redstone Alloy (Redstone + Silicon) Wires in my pack that are LV Superconductors.

For UV: there doesn't seem to be a clear line between UV and MAX, see the MAX Superconductors being used for UV stuff and UV Machine Components taking Neutronium when they should probably take Tritanium. I added UV Superconductors in my pack to make the MAX ones more expensive and move them back but it would be nice to have Gregicality fill this gap as well.

EDIT: All Superconductors should hold 4 Amps per Wire to be consistent with MAX ones and to not make early ones bad,

**Comment by hjae78** [comment]
I want to add UV superconductor
