### ISSUE TITLE
LuV material rework

### ISSUE THREAD

**Issue by hjae78** [Gregicality/gregicality#11]
We talked about changing the LuV material to Rhodium-Palladium but it was pointed out in the discord that Rhodium-Palladium is actually more complex than Osmiridium.  

Regardless of the material chosen, in my opinion, Chrome is a terrible material for LuV.

**Comment by mrpig37** [comment]
Imo: Osmiridium for LuV an Rhodium plated Palladium for ZPM

**Comment by Shattered2909** [comment]
rhodium plated palladium at LuV, its literally made for this

for ZPM we gotta look for something else, osmiridium is not an option, way too easy. maybe something with naquadah or even from tier 1 fusion reactor.

**Comment by hjae78** [comment]
Naqalloy at ZPM?

**Comment by Shattered2909** [comment]
possibly.
