### ISSUE TITLE
Tumbaga EBF time

### ISSUE THREAD

**Issue by schliip** [Gregicality/gregicality#111]
**Tumbaga**, which is required for LV Integral Framework, currently takes **192 seconds** per ingot in the EBF.
![image](https://user-images.githubusercontent.com/34576051/87709849-e6c39d00-c772-11ea-9da2-4bdfe2587180.png)

160 Tumbaga is needed for the **Chemical Plant**, which translates to **8.53 hours** for 1 EBF running on MV power, or just over **2 hours** for 4.

Tumbaga's recipe seems excessively expensive compared to other alloys needed for Integral Frameworks, such as:
Eglin (MV) - 49.25s at MV
Inconel 625 (HV) - 155.2s at MV

**Comment by huneau** [comment]
To be perfectly clear recipe and time are autogenerated using submaterial and temperature. I'm not sure I can change that. But I will take a look

**Comment by hjae78** [comment]
I think these recipes use total mass and not average mass, the same issue we had with matter replicator recipes
