### ISSUE TITLE
Hydrogen Fluoride electrolyzes to Hydrogen and Chlorine

### ISSUE THREAD

**Issue by schliip** [Gregicality/gregicality#112]
![image](https://user-images.githubusercontent.com/34576051/87726016-44b0ae80-c78c-11ea-89d7-979cd956067b.png)
![image](https://user-images.githubusercontent.com/34576051/87726059-51cd9d80-c78c-11ea-87d3-2e648ebd6907.png)
Should return the 1000 Hydrogen and 1000 Fluorine used to make 2000mb Hydrogen Fluoride

**Comment by huneau** [comment]
Hum ok I will take a look
