### ISSUE TITLE
Increase EU/t of recipes in EBF to correspond to the tier of the material

### ISSUE THREAD

**Issue by hjae78** [Gregicality/gregicality#12]
For example Aluminium should take 120 EU/t and keep it's duration, Stainless Steel should be increased to 480 EU/t and it's duration should be halved and Titanium's EU/t should be raised to 1920. Unsure if or how much the duration of this recipe should be changed since it already has a processing chain.

**Comment by Shattered2909** [comment]
change aluminium to take 40 sec at 120 EU/t
stainless to 80 sec at 480 EU/t
titanium from dust 80 sec, from tetrachloride 40 sec, both at 1920 EU/t

the idea of this is to require higher tier energy input and make lower tier materials faster and faster with overclocking (if players choose to do so)

do not take away half the duration of stainless steel. its meant to take HV as a baseline, not MV+overclock

**Comment by mrpig37** [comment]
yes, the tier's casing material should require the same voltage of that tier.
the needed coils for those recipes should be relative to the melting point (which i think it already is).
I also think of a rework in general for the EBF/Volcanos.
If a material is  a blast furnace material, and isn't used in LV recipes at all it should require MV on the EBF, if its a a blast furnace material and isn't used on MV, it should require HV. and so on.
Also, some materials should be volcanos exclusive, and cryogenic freezer exclusive

**Comment by hjae78** [comment]
Decal thinks that locking materials with coils is enough. Only locking it to coils also gives the player the choice whether or not to overclock. Instead I will write a CT script to do this for people that are still interested.
