### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ecr99** [Gregicality/gregicality#120]
I need help , i cant undestand what is crashing my game whenever i try to install gregicality.

Heres the crash log:
[crash-2020-08-01_14.49.26-client.txt](https://github.com/Gregicality/gregicality/files/5011150/crash-2020-08-01_14.49.26-client.txt)

Thanks!

**Comment by hjae78** [comment]
You need the mod JustEnoughIDs, https://www.curseforge.com/minecraft/mc-mods/jeid
