### ISSUE TITLE
Add option to make Naquadah Reactors multiblocks at all tiers?

### ISSUE THREAD

**Issue by hjae78** [Gregicality/gregicality#13]
Thoughts on this? I personally feel singleblock generators above HV is no-no.

**Comment by mrpig37** [comment]
yes, but am more into having exclusivelly multiblocks for generators at EV+

**Comment by Shattered2909** [comment]
if there is a config option for having the singeblocks or not, im okay with the change. current multiblock naquadah reactor is VERY expensive

**Comment by hjae78** [comment]
@Shattered2909 they would absolutely be a lot smaller than the current multiblock naq reactor. Thinking 3x3 or maybe 5x5.

**Comment by huneau** [comment]
There is turbo engine for EV to Luv and then Naquadah reactor for IV to ZPM
Seems for me
