### ISSUE TITLE
Extruder uses wrong electronic parts, circuits and machine hulls

### ISSUE THREAD

**Issue by zhangjunyan2580** [Gregicality/gregicality#131]
MV Extruder uses LV machine hull, LV electric piston and LV Circuit.
HV Extruder uses MV one, EV Extruder uses HV one, others are correct.

**Comment by huneau** [comment]
easy fix, replace old registerMachineRecipe by GTCE one since its a public method

https://github.com/GregTechCE/GregTech/blob/7ee52df7ee0194fdf89e35c8c36e478dbf2b7360/src/main/java/gregtech/loaders/recipe/MetaTileEntityLoader.java#L410
