### ISSUE TITLE
Raw Crystal Chip production

### ISSUE THREAD

**Issue by hjae78** [Gregicality/gregicality#14]
Currently you only need to make Raw Crystal Chips with Europium once and after that you can simply dupe them. Perhaps we should consider if this is the way we want it?

**Comment by Shattered2909** [comment]
my idea:

remove the crystal CPU to raw crystal chip dupe recipe in the cutting machine, thats stupid

now change the autoclave recipes for raw crystal chip to these chances:
75% +5% per tier with exquisite emerald/olivine
25% +5% per tier with flawless emerald/olivine

that way the dupe is gone, but the europium recipe is more useful and it gets better chances with better autoclaves. i also suggest changing the EBF recipe that makes engraved crystal chips from raw crystal chips to LuV voltage (make it take 30720 EU/t), make the heat requirement something between 5400 and 600, keep time as it is

**Comment by huneau** [comment]
exquise + europium= 75%
![image](https://user-images.git
hubusercontent.com/9199240/85131529-46439100-b237-11ea-9fa1-63fd4b9f17bc.png)
flawless + europium= 25%
![image](https://user-images.githubusercontent.com/9199240/85131544-4c397200-b237-11ea-92f2-a92d8dbcebf0.png)
exquise + helium = 7.5%
![image](https://user-images.githubusercontent.com/9199240/85131562-53608000-b237-11ea-9124-05fa35f7f1d1.png)
flawless + helium = 2.5%
![image](https://user-images.githubusercontent.com/9199240/85131573-58bdca80-b237-11ea-94cb-f5a9ff4c3010.png)
Dupe @ZMP tier
![image](https://user-images.githubusercontent.com/9199240/85131605-6a06d700-b237-11ea-9dfe-8581481334ef.png)
dupe with europium using plate
![image](https://user-images.githubusercontent.com/9199240/85131454-21e7b480-b237-11ea-8b89-608665cce88e.png)
dupe with helium using block
![image](https://user-images.githubusercontent.com/9199240/85131466-2b711c80-b237-11ea-9cba-1fa852bc3dc1.png)

@Shattered2909 constructive feedback ?

**Comment by Shattered2909** [comment]
Seems good
