### ISSUE TITLE
Additional recipe for Calcium Chloride

### ISSUE THREAD

**Issue by hjae78** [Gregicality/gregicality#144]
2 NaCl + CaCO3 → Na2CO3 + CaCl2

**Comment by Prunoideae** [comment]
I would suggest 2HCl + CaCO<sub>3</sub> → H<sub>2</sub>O + CO<sub>2</sub> + CaCl<sub>2</sub> .
Reversing a [salt metathesis reaction](https://en.wikipedia.org/wiki/Salt_metathesis_reaction) that produces insoluble substance is not sounding like a doable, at least reasonable idea.
