### ISSUE TITLE
is this a mekanism, gregicallity or a the one probe issue?

### ISSUE THREAD

**Issue by TheXTrunner** [Gregicality/gregicality#147]
talking about the red text, appears with all of the mekanism stuff
![a 2020-08-25 124501](https://user-images.githubusercontent.com/46388285/91256572-aeca5500-e735-11ea-954f-338e7655dd8f.png)

**Comment by Zafaranec** [comment]
Unfortunately have same problem, in server console is bunch of:  [Server thread/ERROR] [gregtech]: Bad One probe Implem: gregicadditions.theoneprobe.MultiRecipeProvider

**Comment by huneau** [comment]
It's something that come back again. What is your one probe version please?

**Comment by Zafaranec** [comment]
I use latest 1.12 version TheOneProbe - 1.12-1.4.28

**Comment by YoungGT** [comment]
Same problem. Using Gregicality 0.20.4, Mekanism 9.8.3.390, TOP 1.4.28 and GTCE 1.9.3.531.

**Comment by huneau** [comment]
fix in 66b2c391

**Comment by Zafaranec** [comment]
Hi, I have only question, I still get console spam from magneticraft and some of Industrial Renewal:

[Server thread/ERROR] [gregtech]: Bad One probe Implem: public class java.lang.IllegalArgumentException Parameter specified as non-null is null: method com.cout970.magneticraft.systems.tileentities.TileBase.getCapability, parameter capability com.cout970.magneticraft.systems.tileentities.TileBase

[Server thread/ERROR] [gregtech]: Bad One probe Implem: public class java.lang.NullPointerException null cassiokf.industrialrenewal.tileentity.TileEntityBulkConveyorHopper

it's a same problem or don't you know, which mod have that problem?
