### ISSUE TITLE
Unable to make steel round due to Ore Dictionary

### ISSUE THREAD

**Issue by YoungGT** [Gregicality/gregicality#148]
All steel round recipes only accept GCTE's steel nuggets, thus using other mods' nuggets cannot make steel round. I don't know if that's also for other materials and recipes. Hope to fix it.

**Comment by Prunoideae** [comment]
https://github.com/Gregicality/gregicality/blob/a19c90b8bfe7fe40afc6489c4eabd69c8e9ae5f6/src/main/java/gregicadditions/recipes/RecipeHandler.java#L330-L331

Here you used only OreDictUnifier.get to get a stack representation of given prefix and material, making it unable to be substituted with other items of same entry. 

Changing this to new UnificationEntry(nugget, material) would fix it.
