### ISSUE TITLE
Naquadah not generating in the end after reboot

### ISSUE THREAD

**Issue by warjort** [Gregicality/gregicality#153]
When you first boot the game, naquadah does generate in the end, but after a second boot of the game the config/gregtech/worldgen/end/naquadah_vein.json is deleted.

gregicadditions.worldgen.WorldGenRegister is checking for config/gregtech/gt_replaced before deleting the file, but this file is never written so on a second boot it removes the overridden vein config thinking it is the base configuration.

Later it checks for config/gregtech/ga_worldgen_7 and does not recopy the override file.

I don't think this is limited to naquadah. Other configs use a xxx-vein2.json naming convention, which avoids the problem.
But that approach means it still tries to delete any xxx-vein.json that might have been added by a mod pack developer, maybe even in a different dimension?

**Comment by huneau** [comment]
ok thx for feedback I will make more testing
