### ISSUE TITLE
Multiblocktweaker Multiblocks not showing Pattern in JEI

### ISSUE THREAD

**Issue by brachy84** [Gregicality/gregicality#155]
Name says it all. Latest version of gregtech, gregciality, and multiblocktweaker. Works fine without Gregciality.

**Comment by LAGIdiot** [comment]
I am going to little bit specify why this is happening. MB Tweaker is using standard GTCE multiblock category in JEI. Which Gregicality disables right here: https://github.com/Gregicality/gregicality/blob/a24e55ae9eeb9b0c3f13ed797fafd1a12f7ef739/src/main/java/gregicadditions/jei/JEIGAPlugin.java#L61

**Comment by huneau** [comment]
YEah, there is a compatibility issue with MB tweaker. its not completely impossible to make it up and running., but I have to find a way to fix it.

**Comment by huneau** [comment]
@LAGIdiot @eutropius225 I need help with that, I try multiple way to use the default multiblock page.
but the JEi seems obscure to hide the multiblock recipe.
I need to hide some GTCE multiblock, because I added casing has oredict and autogenerate block.

**Comment by eutropius225** [comment]
To hide a recipe with JEI, you need to get the recipe category instance, and the recipe (wrapper) instance.

You can look up recipe categories by ID from the `IRecipeRegistry`, and look up recipe wrappers, again from the `IRecipeRegistry`, by using an `IFocus` and the recipe category. Then you can just hide them, also with the `IRecipeRegistry`.
