### ISSUE TITLE
Uranium refinement process

### ISSUE THREAD

**Issue by hjae78** [Gregicality/gregicality#160]
https://cdn.discordapp.com/attachments/704379576742183132/754089317864833034/Pitchblende.png

**Comment by hjae78** [comment]
https://cdn.discordapp.com/attachments/704379576742183132/754104963168206888/2020-09-12_00.23.15.png

**Comment by whatsapp2** [comment]
https://discordapp.com/channels/701354865217110096/704379576742183132/754428818051170305

**Comment by hjae78** [comment]
https://cdn.discordapp.com/attachments/751046016282787872/755845494822928465/Purex.png

**Comment by pablocnvs** [comment]
should be done
