### ISSUE TITLE
Aluminium Processing

### ISSUE THREAD

**Issue by Zalgo239** [Gregicality/gregicality#169]
I made some diagrams for a more realistic Aluminium processing chain and I was told to post them here:

The Bayer Process
![Bayer](https://user-images.githubusercontent.com/67443118/93107059-65748200-f6b1-11ea-864d-2427c14968e2.png)

The Hall-Héroult Process
![Hall-Héroult](https://user-images.githubusercontent.com/67443118/93107407-d87df880-f6b1-11ea-8e78-41b1217cf377.png)

Red Mud Reprocessing
![RedMud](https://user-images.githubusercontent.com/67443118/93107135-791fe880-f6b1-11ea-9c4a-401f9d4d04aa.png)

To make production of HF easier I suggest the following reaction:
CaF2 + H2SO4 → 2 HF + CaSO4
CaF2 is a mineral known as Fluorite, and H2SO4 is sulfuric acid

**Comment by huneau** [comment]
We have to think, *The Bayer Process* and *The Hall-Héroult Process* should be LV process

**Comment by huneau** [comment]
so maybe not hardcore recipes

**Comment by huneau** [comment]
*Red Mud Reprocessing* have to be lower than HV

**Comment by pablocnvs** [comment]
maybe make bauxite produce more aluminum that it would by electrolysis to justify its usage

**Comment by pablocnvs** [comment]
i would make it so that bauxite is smeltable but at a terrible rate, so that aluminium could be obtained for a small quantity but it would be more efficient to do the electrolysis

**Comment by Zalgo239** [comment]
I think having electrolysis still available, but with a low yield and long processing times, and having the chain I explained here is the best option

**Comment by pablocnvs** [comment]
i mean, we can keep the aluminium ore that gives pure aluminium ingots and have this process for bauxite exclusively

**Comment by pablocnvs** [comment]
I'm going to close this as this is fully implemented
