### ISSUE TITLE
ZenScript, if possible, to make volcanos and cryo-freezer exclusive recipes

### ISSUE THREAD

**Issue by mrpig37** [Gregicality/gregicality#17]
It would just be a nice thing to have. like with the large chemical reactor and large forge hammer. 
especially for modpack makers.

**Comment by hjae78** [comment]
Took a look at this and not sure if it's possible, maybe decal can give a definitive answer

**Comment by hjae78** [comment]
@huneau thoughts?

**Comment by huneau** [comment]
@hjae78 not an easy task. there is a possibility but I'm not a fan
