### ISSUE TITLE
Chromium processing

### ISSUE THREAD

**Issue by Zalgo239** [Gregicality/gregicality#171]
I made a diagram for realistic extraction of Chromium from Chromite

![Chromite](https://user-images.githubusercontent.com/67443118/93196915-4c201400-f74b-11ea-8314-ff149f3ca573.png)

The wiki article on Chromium production has the balanced chemical equations
https://en.wikipedia.org/wiki/Chromium#Production

**Comment by huneau** [comment]
ruby possible balanced 
Ruby + Aqua Regia => Ruby slurry 
Ruby slurry + Electrolyze => Chromiun(III) oxide + alumina + ??

**Comment by pablocnvs** [comment]
besides the ruby thing, done
