### ISSUE TITLE
Rare Earth Elements Extraction

### ISSUE THREAD

**Issue by Zalgo239** [Gregicality/gregicality#172]
I made a diagram for a simplified version of a realistic rare earth elements extraction system

![REE](https://user-images.githubusercontent.com/67443118/93250898-c2486900-f793-11ea-86a4-d187e8604f46.png)

I based it loosely on this image taken from a paper

![1-s2 0-S0892687513003452-gr10](https://user-images.githubusercontent.com/67443118/93250933-cd9b9480-f793-11ea-9d90-ae3d84e8daba.jpg)

Link to the original paper:
https://www.sciencedirect.com/science/article/pii/S0892687513003452

**Comment by hjae78** [comment]
chart by pcm_keywielder https://cdn.discordapp.com/attachments/701354865657643070/755561655743545494/Monazite_and_Red_Mud.png
