### ISSUE TITLE
Lithium extraction from ores

### ISSUE THREAD

**Issue by Zalgo239** [Gregicality/gregicality#175]
I made a diagram for the extraction of Lithium from ores

![LithiumOres(1)](https://user-images.githubusercontent.com/67443118/93354932-d3e64b00-f83d-11ea-955e-8e665afe2dc7.png)

**Comment by pablocnvs** [comment]
i would see your diagram working for spodumene, but how are you going to deal with lepidolite, which doesn't have silicon but contains potassium and fluorine?

**Comment by pablocnvs** [comment]
so for lepidolite, i found that adding calcium oxide could drag the fluorine during roasting, and the potassium could be extracted in the sulfide step with a potassium sulfate solution that would then be electrolysed

**Comment by Zalgo239** [comment]
> 
> 
> so for lepidolite, i found that adding calcium oxide could drag the fluorine during roasting, and the potassium could be extracted in the sulfide step with a potassium sulfate solution that would then be electrolysed

Yes, it makes sense, I like it

**Comment by pablocnvs** [comment]
done
