### ISSUE TITLE
Copper electrorefining

### ISSUE THREAD

**Issue by pablocnvs** [Gregicality/gregicality#181]
Here's the copper electrorefinement process, with the electrolysis itself and the processing of the slime

![Copper ElectroRefining](https://user-images.githubusercontent.com/64352555/93717956-48402780-fb79-11ea-9ea7-bb2b99380728.png)

![anodic slime (2)](https://user-images.githubusercontent.com/64352555/93717981-63ab3280-fb79-11ea-90a2-438d1005bf72.png)

As I've explained in the discord, the unrefined copper should be still usable as copper, and the process gives 1.5x more copper, as well as other resources

**Comment by Shattered2909** [comment]
I get that we need more processing chains for later materials, but please do not mess with Copper like that... this will fuck up the early game.

**Comment by pablocnvs** [comment]
done
