### ISSUE TITLE
Suggestions for the next tier of circuits

### ISSUE THREAD

**Issue by Zalgo239** [Gregicality/gregicality#182]
In the past few days I've been working on diagrams for the next tier of circuits, in my head Wetware is supposed to be a cybernetic technology, so the next step would be to have completely biological processors (with some supporting hardware of course).

The first diagrams are for the preparation and sterilization of growth medium
![StemCellGrowthMedium(2)](https://user-images.githubusercontent.com/67443118/93717886-dec01900-fb78-11ea-8780-df06cd808579.png)
![Sulfanilamide](https://user-images.githubusercontent.com/67443118/93717848-b0423e00-fb78-11ea-8dcd-44c6a3fa92c1.png)

These are meant to simulate the real process of creating a growth medium for stem cells and the production and addition of antibiotics to the growth medium

Next is the production and sterilization of petri dish for the cultivation of cells and bacteria
![CleanPetriDish](https://user-images.githubusercontent.com/67443118/93717904-f26b7f80-fb78-11ea-9cca-985be8f46c09.png)

The bacteria needed for some of the processes are basically items looking like a petri dish with some blob inside, bacteria are grown with a special multiblock. Quick Note: The small bacterial cultures should be obtainable from the normal ones, possibly with a crafting table recipe using a clean culture
![BacterialGrowth](https://user-images.githubusercontent.com/67443118/93718220-f39dac00-fb7a-11ea-9cc0-0239d44a2198.png)

I also made growing stem cells more realistic
![StemCellsProduction](https://user-images.githubusercontent.com/67443118/93718238-14660180-fb7b-11ea-869b-a0a661b929ee.png)

If you are wondering how to make an homogenizer, have this:
![Homogenizer(1)](https://user-images.githubusercontent.com/67443118/93718247-1fb92d00-fb7b-11ea-9760-4e389753e1eb.png)

I made a little change to the production of wetware boards. Quick Note: Here the circuit asslines are meant to be just normal assembly lines.
![Wetware_Bio_Boards](https://user-images.githubusercontent.com/67443118/93718283-5b53f700-fb7b-11ea-8cc9-359866bb242d.png)

And finally, the bio circuits themselves
![BioCircuits](https://user-images.githubusercontent.com/67443118/93718289-6444c880-fb7b-11ea-825b-87c48a3c8d4e.png)

**Comment by Armagedon13** [comment]
![4b1847bfc2079e8094836265fd807443](https://user-images.githubusercontent.com/12619078/100143226-c66bc380-2e73-11eb-95cb-652dfdf4da73.jpg)
wtf i just read

**Comment by Houstonruss** [comment]
I came here from GTNH Gigaplex just to ask if you guys are okay.

**Comment by Zalgo239** [comment]
Yes do not worry, you should join us on the path towards perfect balance
