### ISSUE TITLE
New nuclear reactor material

### ISSUE THREAD

**Issue by Zalgo239** [Gregicality/gregicality#184]
I made a process that creates a more realistic material to use for fission reactors instead of just lead
![ReactorVessel](https://user-images.githubusercontent.com/67443118/93808881-dfc27a80-fc4c-11ea-9185-f9a3111d30ab.png)

**Comment by huneau** [comment]
ah nice, its cool

**Comment by huneau** [comment]
I will add it tonight

**Comment by huneau** [comment]
like tiered recipe ?
