### ISSUE TITLE
New Indium extraction chain

### ISSUE THREAD

**Issue by Zalgo239** [Gregicality/gregicality#185]
I made a diagram for Indium extraction
![Indium(1)](https://user-images.githubusercontent.com/67443118/93822614-c62b2e00-fc60-11ea-87e0-48d9e8d3d80d.png)

**Comment by hjae78** [comment]
I'm thinking that this will be a better way of obtaining indium available at perhaps LuV voltage?

**Comment by huneau** [comment]
like tiered recipe ?

**Comment by pablocnvs** [comment]
done
