### ISSUE TITLE
UHV microcrafting

### ISSUE THREAD

**Issue by huneau** [Gregicality/gregicality#192]
add microcrafting with new micro component
We can imagine 
hard drive, 
GPU, 
tiered Ram
thermal sensor, 
accelerometer sensor, 
Pa sensor,
IR sensor
display, 
fuse,
drill bits,
.... 

@hjae78 what do you think ?

**Comment by hjae78** [comment]
Hmm, very interesting, are you thinking that these should be tiered or just one tier?

**Comment by huneau** [comment]
tiered definitively
