### ISSUE TITLE
[Suggestion] Night Vision Goggles

### ISSUE THREAD

**Issue by Shattered2909** [Gregicality/gregicality#196]
Would be nice to have those as well, both as a standalone Item and integrated into the Nano/Quantum Helmet (please have a key to enable/disable Night Vision)

**Comment by Shattered2909** [comment]
![2020-09-23_23 59 17](https://user-images.githubusercontent.com/35029480/94074056-cfe79980-fdf8-11ea-928f-9192047b4654.png)

Night Vision Goggles should take the Glass, Sensors, Emitters and 1 of the Circuits plus an extra Battery, remove those from the Helmet recipe and just make the Helmet require the Goggles

**Comment by shawnbyday** [comment]
Hi, I'm new here but while you're at potentially changing/enhancing night vision goggles if you could make them not blind you in the light that'd be fantastic! Even if it's just the top tier ones that can do that I'd be a huge fan.

**Comment by brachy84** [comment]
this can be closed now @hjae78
