### ISSUE TITLE
A Startup Crash 

### ISSUE THREAD

**Issue by Freebi85** [Gregicality/gregicality#20]
Not sure why exactly tbh. Seems not to happen on 0.19.6

[crash-2020-05-29_21.15.31-client.txt](https://github.com/Gregicality/gregicality/files/4703837/crash-2020-05-29_21.15.31-client.txt)

GregTechCE Version: 1.9.1.481
Gregicality Version: 0.19.8
Forge Version: 14.23.5.2847

**Comment by huneau** [comment]
Hello, 0.19.8 is not compatible with 1.9.1.481 but compatible with 1.9.1.505

**Comment by Freebi85** [comment]
Ah i see. Thank you for the fast answer. Feel free to close if that's the case.

Because i need to wait for this https://github.com/GregTechCE/GregTech/issues/1088 and https://github.com/GregTechCE/GregTech/issues/1086
😄
