### ISSUE TITLE
Unintentional Nuclear Reactor Gating?

### ISSUE THREAD

**Issue by warjort** [Gregicality/gregicality#203]
Apologies if this is intentional.

The nuclear reactor appears to be setup so that you can make everything in the EV tier. While the breeder reactor is IV tier.

However there is one thing required for the nuclear reactor that seems to push it into the IV tier?
To make cladded reactor casing, you need reactor steel which can only be made with a blast alloy furnace, this is nothing higher than HV recipes. The blast alloy furnace itself only uses ingredients from EV including its integral framework.

But the recipe to make it in the assembler requires IV power? Specifically 5000 EU/t

This seems like a mistake? Or maybe I missed something?

**Comment by huneau** [comment]
hum, I probably understand the issue.
Cladded reactor steel -> Dense Reactor Steel -> Blast alloy -> IV assembler
The nuclear reactor is EV stuff and the breeder is IV stuff
so its weird that was gated by IV assembler right ? but for me it seems doable with effort
