### ISSUE TITLE
Offshore Oil Drilling, Space Mining (for AR and GC integration), Uranium from seawater, Memory Foam

### ISSUE THREAD

**Issue by Zalgo239** [Gregicality/gregicality#222]
Offshore Oil Drilling:
![OilDrilling](https://user-images.githubusercontent.com/67443118/95665398-28849980-0b50-11eb-82dc-2eb3aeb95028.png)
![2020-10-09_22 59 11](https://user-images.githubusercontent.com/67443118/95665400-2e7a7a80-0b50-11eb-81d4-c6e75bcb5663.png)

Extraction of resources from AR or GC moon using rovers:
![Rovers](https://user-images.githubusercontent.com/67443118/95665411-4baf4900-0b50-11eb-9dc4-4b1fe2ea9fa4.png)
![MoonRegolith](https://user-images.githubusercontent.com/67443118/95665414-4f42d000-0b50-11eb-973c-7c43a166d0aa.png)

Extraction of Uranium from seawater:
![WholivesinanisotopeUnderthesea](https://user-images.githubusercontent.com/67443118/95665433-71d4e900-0b50-11eb-92fd-e5361fe491cd.png)

And finally, since vanilla beds are overpowered, memory foam beds:
![MemoryFoam](https://user-images.githubusercontent.com/67443118/95665449-86b17c80-0b50-11eb-8d10-68cb035529ca.png)

**Comment by huneau** [comment]
The GC integration will never happen, BUT we can imagine a biome miner configurable for modpack integration

**Comment by Zalgo239** [comment]
That would probably be a better alternative yes
