### ISSUE TITLE
Platinum processing chlorine usage

### ISSUE THREAD

**Issue by schliip** [Gregicality/gregicality#232]
Currently, Pt processing requires **1b Chlorine per Pt metallic powder processed**, due to the Aqua Regia using 1b HCl. Platinum Concentrate returns 1b NO2 and 1b Diluted Sulfuric Acid per 2b concentrate.

Cl usage adds up quickly, due to the "loop" where salts are recycled back into Pt metallic powder. 

In the original Pt processing line from Bartworks/GT:NH, 2b Aqua Regia was made from 1b HCl + 1b diluted sulfuric acid.
This made Aqua Regia a **closed loop** in Pt processing, needing only water and oxygen input. 

I think the Cl usage of Pt processing is currently far too high, given the new (more realistic) Aqua Regia recipe combined with Pt line designed for the old recipe.

I suggest:
**Change Platinum Concentrate to return HCl or Chlorine instead of Diluted Sulfuric Acid.**
This reflects the Gregicality recipe for Aqua Regia, which uses HCl instead of diluted sulfuric acid. The exact amount of HCl or Chlorine returned depends on the desired balance. I suggest at least 1b.

**Comment by huneau** [comment]
Nice suggestion, I will take a look
