### ISSUE TITLE
[Request] Stop using GTCE logger as it causes confusion

### ISSUE THREAD

**Issue by LAGIdiot** [Gregicality/gregicality#233]
**Gregicality** is using **GTCE's logging capabilities** which causes confusion and **GTCE** is getting bug reports which belongs to **Gregicality**. Currently we have two reports:

https://github.com/GregTechCE/GregTech/issues/1283 reported by @Zafaranec
https://github.com/GregTechCE/GregTech/issues/1217 reported by @XIPure

So I would like to request from you to **stop using GTCE's logger** if possible as soon as in next release. I am not planing to make it internal even if it would be solution for GTCE as well (as it would break you). Also feel free to make copies of provided issues so you can properly handle them as I will close them on GTCE side.

**Comment by huneau** [comment]
the fix is in this old commit 81afea7038de0b7e43b4864f00d5151d03dc1820
but not into the master branch, I will do this in the evening

**Comment by LAGIdiot** [comment]
Good to read that you are aware of this and that you already prepared fix for it.

**Comment by huneau** [comment]
yeah, I'm sorry for the inconvenience.
