### ISSUE TITLE
 [Feature] More information inside large transformer gui

### ISSUE THREAD

**Issue by XXxinsanityxX** [Gregicality/gregicality#24]
Energy In, Energy Out, Amps In, Amps Out stuff like that just to have a more complete understanding of the multi performance.

**Comment by hjae78** [comment]
Are you interested in seeing the average energy in/out?

**Comment by huneau** [comment]
be careful it's not an easy task the average energy in and out

**Comment by XXxinsanityxX** [comment]
Average is not needed, showing how much eu/amps goes in and how much eu/amps is going out is enough. Basically just reading the info of the hatches it has and displaying it on the gui so its not empty. The averages would be nice but they would fit more in some sort of handheld scanner like gt5 or in the big battery multi perhaps.

**Comment by huneau** [comment]
![image](https://user-images.githubusercontent.com/9199240/85197366-d4c01d00-b2e0-11ea-9106-6e53c197e48c.png)
