### ISSUE TITLE
Quest for steel

### ISSUE THREAD

**Issue by LOMS** [Gregicality/gregicality#249]
I bumped into a silly situation.
I have this:
![изображение](https://user-images.githubusercontent.com/2064587/99899491-c4aad000-2cba-11eb-90e2-6caa2e64d196.png)
But yet I have this:
![изображение](https://user-images.githubusercontent.com/2064587/99899503-e73ce900-2cba-11eb-9af8-14adf6853394.png)
I never have held this much of fireclay dust, because I was rushing for steel and turned it into bricks fast, so technically quest isn't completed, but logically if I have steel - this quest is completed.
This is locked behind this quest too.
![изображение](https://user-images.githubusercontent.com/2064587/99899539-3b47cd80-2cbb-11eb-81d5-d7526442dcdf.png)

Probably, it would be nicer to keep quest numbers to 1 and have recomendations for the actual quantities, that player should make.

**Comment by huneau** [comment]
moved to https://github.com/Gregicality/gregicality-skyblock-edition/issues/2
