### ISSUE TITLE
Steam Mixer Recipe Map

### ISSUE THREAD

**Issue by Shattered2909** [Gregicality/gregicality#266]
The Steam Mixer is currently pretty useless, giving it it's own recipe map would allow me to use it for some things pre LV tier.

Is it still Fluid output only or does it have an Item output slot?

**Comment by MammothKryptonite** [comment]
Seconded. This would also be useful for our pack.

**Comment by hjae78** [comment]
I talked about this with decal and we decided that it's superfluous, this behavior can be accomplished by simply adding a recipe to mixer with EU/t <= 8 as that's the limit of recipes in steam machines.
