### ISSUE TITLE
Degenerate Rhenium Plasma Cell Textures

### ISSUE THREAD

**Issue by whatsapp2** [Gregicality/gregicality#277]
Empty Cell
![Rh Cell](https://user-images.githubusercontent.com/25994176/102263236-a612b000-3ed9-11eb-88bf-ae79915a3f81.png)

Full Cell
![spectral_arrow](https://user-images.githubusercontent.com/25994176/102263299-baef4380-3ed9-11eb-8b86-f36c9924b87a.png)

Mcmeta (You can tweak this if textures cycle too quickly):
{
	"animation": {
		"interpolate": true,
		"frametime": 5,
                "frames":[0,7,1,2,3,4,5,6,7]
	}
}

**Comment by hjae78** [comment]
Thank you so much!
