### ISSUE TITLE
[Feature] Option to disable energy converters independently 

### ISSUE THREAD

**Issue by XXxinsanityxX** [Gregicality/gregicality#28]
Currently you can only disable both of the converter types, you cant disable only one type.

Also one thing is that the converters only output energy while they are receiving energy, they can have a full buffer but if they are not receiving any energy they will not empty its buffer.

**Comment by huneau** [comment]
fix in https://github.com/Gregicality/gregicality/commit/96016de582472f5187f67ce3aad5539669ad4e6c
