### ISSUE TITLE
[TCon API] Trying to register a modifier with the name trait_supertic_osmium but it already is registered

### ISSUE THREAD

**Issue by border999** [Gregicality/gregicality#288]
[crash-2020-12-25_03.11.32-client.txt](https://github.com/Gregicality/gregicality/files/5742008/crash-2020-12-25_03.11.32-client.txt)

**Comment by huneau** [comment]
Hum, with you log, the only thing I can imagine is, you try to register trait_supertic_osmium with GTCE material with TCon.
Gregicality should register for you TCon material

**Comment by border999** [comment]
I apologize if you said the solution in that statement and I just didn't understand. But what do you suggest as a fix?

**Comment by huneau** [comment]
you should remove TCon material registration

**Comment by border999** [comment]
can I do that with your config or do I need to do it on tinkers' end?

**Comment by huneau** [comment]
send me a sample of your conf/script otherwise I cannot help you more

**Comment by border999** [comment]
[gtadditions.zip](https://github.com/Gregicality/gregicality/files/5742836/gtadditions.zip)
[tconstruct.zip](https://github.com/Gregicality/gregicality/files/5742838/tconstruct.zip)

**Comment by border999** [comment]
https://gist.github.com/border999/5139dafeb615eb9cd8fb7d411fd341f6
https://gist.github.com/border999/e525facd072c836cf85944f1bf2acaef

**Comment by magcicada** [comment]
Find your conf`plustic.cfg` in the `config` file,and disable `"Enable material osmiridium"` and `"Enable material osmium"`.

**Comment by magcicada** [comment]
And disable all of osmium in the config of supertic.

**Comment by border999** [comment]
https://gist.github.com/border999/8ce2c4ff280deb7dceaa580182c27cd5
[crash-2020-12-27_01.54.39-client.txt](https://github.com/Gregicality/gregicality/files/5744510/crash-2020-12-27_01.54.39-client.txt)
There is no config for SuperTic. Disabled osmium and osmiridium in Plustic, crash still occurs.

**Comment by border999** [comment]
regenerating config, seeing if it appears then.

**Comment by magcicada** [comment]
send me the `Effects.xml` of SuperTic,Should be disabled osmium in it.

**Comment by border999** [comment]
https://gist.github.com/border999/d712c0b1751d3bedce93027cd2650c3a

**Comment by magcicada** [comment]
Nothing at all?

**Comment by border999** [comment]
nothing

**Comment by magcicada** [comment]
If this is the case, you must make a choice.Either delete supertic, or disable `"Tinker's metal tools"` in Gregcality.Because Grecality cannot disable a single material。

**Comment by border999** [comment]
what would be lost if I disable that?

**Comment by magcicada** [comment]
All GT materials for Tic tools.

**Comment by border999** [comment]
think there's any way on your end to correct the issue? I'll try the config disable for the time being. Also removing SuperTic because I don't really use it.

**Comment by border999** [comment]
seems like disabling metal tools worked for the moment, loading up. It might help if you're mod check to see if any other mod is trying to load the same materials.

**Comment by magcicada** [comment]
Tic cannot register the same material twice at the same time Instance,Either it will crash or the material will be overwritten,it depends on the mod how to registered the materials.I can't help you,sorry.

**Comment by magcicada** [comment]
I think you should report this issue to the SuperTic.

**Comment by border999** [comment]
I'm gonna flip back on metal tools and see if removing SuperTic fixes it.

**Comment by border999** [comment]
removing SuperTic fixed it, it's loading.

**Comment by border999** [comment]
reported it to SuperTic's github. It seems VERY unlikely to be responded to. Last issue posted was over a year ago. Seems like and abandoned mod.
