### ISSUE TITLE
Halide Lamp Textures

### ISSUE THREAD

**Issue by whatsapp2** [Gregicality/gregicality#297]
**No lamp core:**
![Hallide lamp (no color)](https://user-images.githubusercontent.com/25994176/103445616-425be700-4c3c-11eb-8bda-fcd15e4e6d9d.png)

**Red Halide Lamp:**
![Hallide lamp red](https://user-images.githubusercontent.com/25994176/103445618-42f47d80-4c3c-11eb-9188-e7d4bb802b5e.png)

**Green Halide Lamp:**
![Hallide lamp green](https://user-images.githubusercontent.com/25994176/103445619-438d1400-4c3c-11eb-8082-23c9504c3f31.png)

**Blue Halide Lamp:**
![Hallide lamp blue](https://user-images.githubusercontent.com/25994176/103445620-438d1400-4c3c-11eb-9ce7-d2b3eaa4775b.png)

**UVA Halide Lamp:**
![Hallide lamp uva](https://user-images.githubusercontent.com/25994176/103445621-4425aa80-4c3c-11eb-9a13-eda8d191a6e0.png)

**White Halide Lamp:**
![Hallide lamp white](https://user-images.githubusercontent.com/25994176/103445622-4425aa80-4c3c-11eb-82fa-510ebe7e6783.png)

**Comment by pablocnvs** [comment]
thx for the textures

**Comment by hjae78** [comment]
Thank you!
