### ISSUE TITLE
[Suggestion] Add a 4 Small Stone Dust to GT5U Stone Dust Centrifuge output recipe

### ISSUE THREAD

**Issue by zeebrandonite** [Gregicality/gregicality#303]
I had a world in 1.7.10 where I built a factory that uses cobblestone,
 water, and air to make virtually anything and this recipe was such a great help in my endeavors. Having that recipe back would be greatly appreciated.
![very good recipe](https://user-images.githubusercontent.com/55376363/103486826-bc23da00-4dce-11eb-947e-684218dffc80.PNG)

**Comment by hjae78** [comment]
For now this isn't something we will add, this is very simple for you to add yourself using CraftTweaker and I think I saw you post about this in GTCE Discord as well so you should have resolved this on your own.
