### ISSUE TITLE
Crash on startup after 0.21.x update

### ISSUE THREAD

**Issue by Max039** [Gregicality/gregicality#304]
Hello,
I really like your mod, appreciate your work and enjoyed playing with your mod for quiet some time now. Though while I updated a custom modpack for me and my friends I found the new version of your mod version 0.21.1 and encountered a problem on startup.

Chrash log : https://pastebin.ubuntu.com/p/62DTVHg4YD/

Vanilla fix only told me that gregicality was the only mod involved but if you need me to pin down anther mod that causes the crash please tell me.

**Comment by huneau** [comment]
Hello @Max039, thanks for feedback.

We will take a look at the issue, seems to be an issue on the server and not on single player.

**Comment by hjae78** [comment]
External Tweaker causes this crash. I have no idea why though
