### ISSUE TITLE
Bose-Einstein Textures?

### ISSUE THREAD

**Issue by whatsapp2** [Gregicality/gregicality#314]
**Empty Cell:**
![Empty Bose-Einstein](https://user-images.githubusercontent.com/25994176/104116236-5a86d280-52dc-11eb-8f1f-b2bcd0ad7f69.png)

**Bose-Einstein Cell:**
![Bose Einstein Cell](https://user-images.githubusercontent.com/25994176/104116244-6ffbfc80-52dc-11eb-8931-5fcb1ed9f727.png)

**.mcmeta for animating the texture:**

{
	"animation": {
		"interpolate": true,
		"frametime": 4,
                "frames":[0,1,2,3,4,5,6]
	}
}

**Comment by pablocnvs** [comment]
i've added them now

**Comment by hjae78** [comment]
👍
