### ISSUE TITLE
Add ULV Busses To IPBF

### ISSUE THREAD

**Issue by DStrand1** [Gregicality/gregicality#318]
Currently, the Industrial Primitive Blast Furnace will not form if it is with ULV Input and Output Busses. I think this should be changed to allow for them, as Steel is a relatively expensive material to invest into it, letting players use Wrought Iron instead.

**Comment by DStrand1** [comment]
I can write the PR for this if it gets approved, as I'm sure it is very low priority at the moment.

**Comment by DStrand1** [comment]
After further inspection, I realize that ULV busses do not work since the recipe for Steel requires 2 distinct inputs and outputs. However, the multiblock still does not form when expanded to have 2 ULV input busses, and 2 ULV output busses. I believe this formation should be allowed, given the construction rules for the multiblock.

**Comment by huneau** [comment]
Its expected that the IPBF use steel to get the LV intput and output bus.
I have the feeling that is a fair cost to speed up the steel process plus, automate the steel production
