### ISSUE TITLE
Simple Ore Washer to ULV

### ISSUE THREAD

**Issue by DStrand1** [Gregicality/gregicality#319]
Currently, the Simple Ore Washer is an LV machine, which kind of defeats the purpose, since you can just make the normal Ore Washer to get your byproducts instead. I suggest it be bumped down to ULV, similar to how it was done in GT5U.

**Comment by huneau** [comment]
The simple ore washer is not better than the normal Ore Washer.

- The simple ore washer is faster and gives dust material
- The normal Ore washer is slower and gives purified dust material

But I understand that the early game should be changed

**Comment by DStrand1** [comment]
I understand that it's not meant to be better, but for roughly the same cost to create, it seems like a waste at the moment. If it only took a ULV Hull and nearly no power, I feel like it would be more useful

**Comment by hjae78** [comment]
It's plenty useful to me, I'm at luv in my playthrough and have used it extensively since lv. I'll look into changing the recipe though

**Comment by DStrand1** [comment]
Thank you. I understand that it still can definitely have its uses, I just personally feel like its hard to justify spending the steel on it in LV, pre-EBF at least. But maybe I'm just reminiscent of how GT5 did it.
