### ISSUE TITLE
Steam Rock Breaker only output cobblestone 

### ISSUE THREAD

**Issue by vfyjxf** [Gregicality/gregicality#321]
Steam Rock Breaker has no redstone signal,this seems to be a problem with gtce.When i use gtce 1.10.5.582,my Steam Rock Breaker works fine ,but when i use gtce 1.10.8.599,it only output cobblestone,and top display it have no redstone signal.My gregicality version is 0.21.0.
![2021-01-16_12 27 35](https://user-images.githubusercontent.com/42764413/104797933-3efc5a00-57fd-11eb-8941-a4c2234214cc.png)
![2021-01-16_12 55 55](https://user-images.githubusercontent.com/42764413/104797947-563b4780-57fd-11eb-9168-2153fde25371.png)

**Comment by hjae78** [comment]
Fixed in newer version!
