### ISSUE TITLE
New Textures

### ISSUE THREAD

**Issue by whatsapp2** [Gregicality/gregicality#348]
.mcmeta of all "X" TCDU cells:

```
{
    "animation": {

        "frametime": 3,

        "frames": [
            0, 1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1, 0]

    }

}
```

Kerr TCDU:
![animation kerr](https://user-images.githubusercontent.com/25994176/106815753-ebca3a00-6639-11eb-8b24-b0bfa871dee1.png)
Newmann TCDU
![animation newmann](https://user-images.githubusercontent.com/25994176/106815756-ecfb6700-6639-11eb-85bc-ac31b1063b4a.png)
Reissner TCDU:
![animation reissner](https://user-images.githubusercontent.com/25994176/106815758-ecfb6700-6639-11eb-8cfd-d556b521c6d4.png)
Empty TCDU:
![TCDU cell](https://user-images.githubusercontent.com/25994176/106815808-06041800-663a-11eb-808f-c511e96e3229.png)
Separation Electromagnet:
![Separation Electromagnet](https://user-images.githubusercontent.com/25994176/106815896-292ec780-663a-11eb-9e49-db41cf237b8d.png)

More to come... still working on them

**Comment by whatsapp2** [comment]
Nanotome from **Pcm_Keywielder**
![nanotome](https://user-images.githubusercontent.com/25994176/106817998-45803380-663d-11eb-8a65-9396a9aaae18.png)

**Comment by whatsapp2** [comment]
Hallide lamp core blue:
![Hallide lamp core blue](https://user-images.githubusercontent.com/25994176/106819101-f1764e80-663e-11eb-97bd-fe7fca422499.png)
Hallide lamp core green:
![Hallide lamp core green](https://user-images.githubusercontent.com/25994176/106819104-f20ee500-663e-11eb-9d70-ddb935a3a36d.png)
Hallide lamp core red:
![Hallide lamp core red](https://user-images.githubusercontent.com/25994176/106819106-f2a77b80-663e-11eb-9dfb-05a66548420a.png)
Hallide lamp core UVA:
![Hallide lamp core uva](https://user-images.githubusercontent.com/25994176/106819113-f63b0280-663e-11eb-9bf3-cda2d685c995.png)
Hallide lamp core white:
![Hallide lamp core white](https://user-images.githubusercontent.com/25994176/106819114-f63b0280-663e-11eb-989e-a24a4fc82147.png)

**Comment by whatsapp2** [comment]
Low-Frequency Laser:
![Low-Frequency Laser](https://user-images.githubusercontent.com/25994176/106844683-d15e8380-666e-11eb-9890-ad8e32164d01.png)
Mid-Frequency Laser:
![Mid-Frequency Laser](https://user-images.githubusercontent.com/25994176/106844684-d15e8380-666e-11eb-8bc0-9c9d1f9528ef.png)
High-Frequency Laser:
![High-Frequency Laser](https://user-images.githubusercontent.com/25994176/106844685-d1f71a00-666e-11eb-88c1-0444dfc1f291.png)

**Comment by hjae78** [comment]
Great job!
