### ISSUE TITLE
[BUG] GTCE pipe recipes not removed

### ISSUE THREAD

**Issue by Akiraca** [Gregicality/gregicality#359]
Currently, GTCE small/medium pipe recipes are not removed, resulted in duplicate crafting pathways with either curved or non-curved plates.
![QQ图片20210208005526](https://user-images.githubusercontent.com/23720781/107153465-ad6dab80-69a8-11eb-94db-3c3c2be9510a.png)

**Comment by hjae78** [comment]
This is fixed in the latest version or it is fixed in the next release, I am not sure when I fixed it
