### ISSUE TITLE
Multiblock Recipe Logic Problems

### ISSUE THREAD

**Issue by DStrand1** [Gregicality/gregicality#361]
Currently, our nested class `LargeSimpleMultiblockRecipeLogic` in the `LargeSimpleRecipeMapMultiblockController` class takes code from the Multi Smelter to do recipes in parallel. However, when this logic was copied over, the Multi Smelter had issues with voiding outputs, and still has issues with recipe detection at times.

Some of these issues have been fixed, but some of them are still being actively worked on for GTCE. Once these fixes are finalized, we should make sure to update our `LargeSimpleMultiblockRecipeLogic` class to remove these issues from us as well, since we almost certainly have them due to how the code was implemented.

**Comment by huneau** [comment]
its an issue introduced by GTCE ALongStringOfNumbers made a fix for that

**Comment by huneau** [comment]
should be related to that 
https://github.com/GregTechCE/GregTech/pull/1384

**Comment by DStrand1** [comment]
Yeah, its mostly fixed for GTCE, but they still have an issue being worked on for it regarding recipe detection.
