### ISSUE TITLE
Missing Texture in version 0.21.4

### ISSUE THREAD

**Issue by whatsapp2** [Gregicality/gregicality#363]
Electron source:
![electron source](https://user-images.githubusercontent.com/25994176/107434232-1c095100-6af0-11eb-8768-5bc929895084.png)

**Comment by Zalgo239** [comment]
Ultrashort pulse laser 16x16
![ultrashort_pulse_laser](https://user-images.githubusercontent.com/67443118/107435956-2990fc00-6b2d-11eb-83e5-335391823342.png)

**Comment by Zalgo239** [comment]
Manifold oscillatory power cell 16x16
![manifold oscillatory power cell](https://user-images.githubusercontent.com/67443118/107437697-ade47e80-6b2f-11eb-827a-b46dad303d71.png)

**Comment by Zalgo239** [comment]
Relativistic spinorial unit, with mcmeta file for animation in the zip
![relativistic spinorial unit](https://user-images.githubusercontent.com/67443118/107439269-15033280-6b32-11eb-9fa0-65d4c040b568.png)
[relativistic.spinorial.unit.png.mcmeta.zip](https://github.com/Gregicality/gregicality/files/5954742/relativistic.spinorial.unit.png.mcmeta.zip)

**Comment by pablocnvs** [comment]
Cosmic mesh containment unit
![cosmic mesh containment unit](https://user-images.githubusercontent.com/64352555/107441869-50076500-6b36-11eb-93a6-79284e400a71.png)

[cosmic.mesh.containment.unit.png.zip](https://github.com/Gregicality/gregicality/files/5954861/cosmic.mesh.containment.unit.png.zip)

**Comment by pablocnvs** [comment]
Contained Exotic Matter:

![contained exotic matter](https://user-images.githubusercontent.com/64352555/107616567-a10a7c80-6c4e-11eb-907b-87ddf646b1dd.png)

Contained High Density Protonic Matter:

![contained high density protonic matter](https://user-images.githubusercontent.com/64352555/107616568-a1a31300-6c4e-11eb-9bce-8ca379b5d482.png)

(Same mcmeta as the contained singularities)

**Comment by Zalgo239** [comment]
Eigenfolded Kerr Manifold
![Eigenfolded kerr manifold](https://user-images.githubusercontent.com/67443118/107702533-ac938d00-6cba-11eb-9e2c-2899409ce515.png)
[eigenfolded.kerr.manifold.mcmeta.zip](https://github.com/Gregicality/gregicality/files/5968609/eigenfolded.kerr.manifold.mcmeta.zip)

**Comment by pablocnvs** [comment]
Sphere Field Shape

![sphere field shape](https://user-images.githubusercontent.com/64352555/107703595-22e4bf00-6cbc-11eb-8612-797c3c3444a6.png)

**Comment by pablocnvs** [comment]
Grating Lithography Mask:

![grating_lithography_mask](https://user-images.githubusercontent.com/64352555/107704932-4f013f80-6cbe-11eb-91a9-8db63ac118c9.png)

**Comment by pablocnvs** [comment]
Scintillator Crystal and Lepton Trap Crystal

![scintilator_crystal](https://user-images.githubusercontent.com/64352555/109343730-13de3f00-786e-11eb-8361-0bb127c43066.png)
![lepton_trap_crystal](https://user-images.githubusercontent.com/64352555/109343729-1345a880-786e-11eb-8614-83feb05aa5e4.png)

**Comment by Regian24** [comment]
Nuclear Clock
Graviton Transducer
Scintillator


![nuclearclock](https://user-images.githubusercontent.com/64612588/111085848-8cedbf80-8519-11eb-95da-84bfa2b7539c.png)
![gravitontransducer](https://user-images.githubusercontent.com/64612588/111085849-8d865600-8519-11eb-962d-041bb37119ea.png)
![scintillator](https://user-images.githubusercontent.com/64612588/111085850-8d865600-8519-11eb-8da3-65bbb2c69798.png)

**Comment by pablocnvs** [comment]
- [x] -Cosmic mesh containment unit
- [x] -Eigenfolded Kerr manifold 
- [ ] -Qunatumchromodyanamic protective plating 
- [x] -Manifold oscillatory cell
- [x] -Nuclear clock                                                           
- [x] -Gravitation transducer
- [x] -Relativistic spinorial unit 
- [ ] -Topological manipulator unit
- [x] -Ultrashort pulse laser
- [x] -Grating lithography mask
- [x] -Lepton trap crystal
- [x] -Scintillator
- [x] -Scintillator crystal 
- [x] -Sphere field shape
- [x] -Contained exotic matter
- [x] -Contained high density protonic matter
- [x] -Electron source
- [ ] -Rotating transparent surface
- [x] -Magnetic trap *
- [x] -Laser cooling unit *
- [x] -Laser diode *
- [ ] -Rig drill
- [ ] -Well conector pipe
- [ ] -Well pipe
- [x] -Uranium saturated yarn
- [x] -Rapidly rotating crucible
- [ ] -Dust field shape
- [x] -Leptonic charge
- [x] -Quantum chromodynamic charge

**Comment by Regian24** [comment]
so what we need is:
 -Qunatumchromodyanamic protective plating
 -Topological manipulator unit
 -Rotating transparent surface


i'm assuming the rotating transparent surface is animated, if that's the case I can't do it, because I suck lol.
can someone give me an overview of what those should look like? I'll make them tomorrow

**Comment by Regian24** [comment]
![topological_manipulator_unit](https://user-images.githubusercontent.com/64612588/111131168-44192380-8578-11eb-9a4a-907f3caecdd2.png)
topological manipulator unit

**Comment by Regian24** [comment]
![rapidlyrotatingcrucible](https://user-images.githubusercontent.com/64612588/111141663-1639dc00-8584-11eb-8155-320a556df7c3.png)


{
"animation": {
"interpolate": false,
"frametime": 2,
"frames":[0,1,2,3]
}
}
