### ISSUE TITLE
in compressor, wheat have two recipes

### ISSUE THREAD

**Issue by JackMeds** [Gregicality/gregicality#364]
![image](https://user-images.githubusercontent.com/38741783/107466886-c5f3e680-6b9f-11eb-923f-cda9e9e867ef.png)
![image](https://user-images.githubusercontent.com/38741783/107466916-c8eed700-6b9f-11eb-8f2e-09429fed93ba.png)

**Comment by DStrand1** [comment]
Issue will be addressed by https://github.com/GregTechCE/GregTech/pull/1488
