### ISSUE TITLE
On the formula of aluminum in blast furnace

### ISSUE THREAD

**Issue by JackMeds** [Gregicality/gregicality#366]
![image](https://user-images.githubusercontent.com/38741783/107467441-fc7e3100-6ba0-11eb-8158-5ffaed0cd01a.png)
![image](https://user-images.githubusercontent.com/38741783/107467455-03a53f00-6ba1-11eb-843f-df31cbd24301.png)
![image](https://user-images.githubusercontent.com/38741783/107467474-099b2000-6ba1-11eb-95ce-3e0bb5a7f97d.png)
![image](https://user-images.githubusercontent.com/38741783/107467478-0dc73d80-6ba1-11eb-9033-967aa638cd67.png)
In fact, it just work on the first recipe

**Comment by pablocnvs** [comment]
Maybe we could add nitrogen to the input and output of the aluminium dust to ingot recipe to make the first recipe different. The nitrogen isn't consumed, and i think it is a better alternative than adding a configuration circuit.
