### ISSUE TITLE
Wrong Recipe

### ISSUE THREAD

**Issue by HoshinoTented** [Gregicality/gregicality#374]
Wrong recipe about Epichlorohydrin in 0.21.4:
![QQ图片20210222192740](https://user-images.githubusercontent.com/25280943/108702369-1fff8f00-7544-11eb-8eb6-98fa69610142.png)

Correct one in 0.21.3:
![image](https://user-images.githubusercontent.com/25280943/108702217-eaf33c80-7543-11eb-8069-2adb125f8d45.png)

**Comment by hjae78** [comment]
Fixed in next release
