### ISSUE TITLE
Change some Multiblock Controller Overlays

### ISSUE THREAD

**Issue by DStrand1** [Gregicality/gregicality#379]
As of GTCE 1.12.0, there is a new feature which allows multiblocks to override a method `RecipeMapMultiblockController#getFrontOverlay()` which our multiblocks (aside from Steam) are child classes of.

The pull request for this: https://github.com/GregTechCE/GregTech/pull/1494

I am opening this issue as a discussion place for changing some of our multiblock overlays, since all of ours still use the default one, and I think we could do more interesting and exciting things with them.

**Comment by TechLord22** [comment]
Here are my ideas (which I've sent on discord as well). For starters, I think every multiblock with a corresponding singleblock machine should have it's overlay changed to the singleblock's front overlay. In some cases, obviously other sides of the singleblock might be better. Custom front overlays for all of the multiblocks would obviously also be something nice, especially for the unique ones.

I also think it would be very cool to do a 3x3 style overlay, similar to the large turbine rotor holder. If there are no hatches on the face of the multiblock containing the controller, change the overlay to be a larger version of the singleblock overlay that covers a 3x3 blockspace (or a unique one), and if there are hatches within that area, use the 1x1 overlay instead.

**Comment by hjae78** [comment]
As far as I know this is now merged
