### ISSUE TITLE
Some Conflicted Recipes

### ISSUE THREAD

**Issue by openipka** [Gregicality/gregicality#384]
### Mod Used
Gregicality-1.12.2-0.21.3
gregtech-1.12.2-1.11.1.632-sources
gregtech-1.12.2-1.11.1.632-energy-api
gregtech-1.12.2-1.11.1.632
CodeChickenLib-1.12.2-3.2.3.358-universal

### Issue Found
![2021-02-27_114948](https://user-images.githubusercontent.com/78248875/109374679-fa7ed680-78f1-11eb-9025-fa0566063696.png)

Barium Oxide with Aluminum dust to Barium Ingot and Barium Aluminate. 
In this situation the 'aluminum dust to Aluminum Ingot' will take precedence over this recipe, which makes this recipe to produce Barium ingot impossible. You may need a circuit to distinguish these two recipes.

![2021-02-27_120019](https://user-images.githubusercontent.com/78248875/109374884-7a597080-78f3-11eb-9720-a2282b8583be.png)
![2021-02-27_120042](https://user-images.githubusercontent.com/78248875/109374887-7b8a9d80-78f3-11eb-8924-792ef68f8fb7.png)

The recipe to make Drilling Mud.
The issue exists in this: Bentonite Clay Solution is impossible to make according to my JEI.
And to mix Clay, Bentonite and Water you get Barium Sulfate Solution, which doesn't make sense.
I believe this is a bug.

### My Consideration
In the first issue, no doubt that Barium plays a vital role in game progress. If this recipe doesn't work, it will be rather difficult to go on. For example, Yttrium Barium Cuprate.
And the Second issue, without Drilling Mud it equals to ban the Drilling Rig, which needs Drilling Mud to operate. Well, it doesn't  affect the game progress as critical as above, but it still useful when we start mass production.

**Comment by openipka** [comment]
### Another issue found:
![2021-02-27_235607](https://user-images.githubusercontent.com/78248875/109392562-c3dba700-7957-11eb-8c83-c5fbc410ee21.png)
![2021-02-27_235624](https://user-images.githubusercontent.com/78248875/109392564-c5a56a80-7957-11eb-8e2c-ad14b0fefcd7.png)
The recipes to make emitters and sensors at same voltage level ( take HV as an example).
The problem is that comparing emitter and sensor, the only different is that sensor requires another 8 foil and the rest is as same as the emitter. **So it always runs the emitter recipe rather than the sensor recipe when the materials are abundant.**

**Comment by hjae78** [comment]
You should update to latest version as that will fix some of the issues in your first post

**Comment by openipka** [comment]
### Yes, I have upgraded my mod to the latest version and the Drilling Mud recipe is clear now.
Here is a new problem:
![2021-02-28_143232](https://user-images.githubusercontent.com/78248875/109410040-5a4cae80-79d2-11eb-8fc0-164d199646a8.png)
![2021-02-28_143322](https://user-images.githubusercontent.com/78248875/109410042-5b7ddb80-79d2-11eb-97c7-cd605a820860.png)
The recipes to produce Epichlorohydrin. and NaClO.
The problem is that **NaOH always reacts with HCIO first and ignores Allyl Chloride, which makes Epichlorohydrin unable to produce in any Chemical Reactors voltage above LV.**
