### ISSUE TITLE
Recipe of making H2SO4 by mixing O2 and H2S in Chemical Reactor is overridden

### ISSUE THREAD

**Issue by openipka** [Gregicality/gregicality#390]
### Mod Used
Gregicality-1.12.2-0.21.3
gregtech-1.12.2-1.11.1.632-sources
gregtech-1.12.2-1.11.1.632-energy-api
gregtech-1.12.2-1.11.1.632
CodeChickenLib-1.12.2-3.2.3.358-universal

### Issue
![2021-03-03_232414](https://user-images.githubusercontent.com/78248875/109828494-a3715c80-7c77-11eb-82f0-306eb3c0abab.png)
![2021-03-03_232423](https://user-images.githubusercontent.com/78248875/109828502-a4a28980-7c77-11eb-99ce-ddefee76f5d6.png)

As showed above, there are 2 recipes different only in the amount of O2.
**Since the recipe of H2SO4 consumes 1000mb more O2 than the other, it is overridden by the other.**

**Comment by TechLord22** [comment]
This will probably be addressed in #388. Thank you for finding this.

**Comment by DStrand1** [comment]
Actually, this is a GTCE recipe problem, but is addressed in https://github.com/GregTechCE/GregTech/pull/1492

**Comment by DStrand1** [comment]
Closed as of GTCE-1.13.0
