### ISSUE TITLE
recipe conflict

### ISSUE THREAD

**Issue by Pnc6lx** [Gregicality/gregicality#392]
recipe
2BaO+2Al→Ba(ingot)+2Al2O3
is uncraftable. 
blast furnace will alway do the Al(dust)→Al(ingot)  recipe first. That make barium unobtainable. 
maybe we can add programmed circuit in all simple dust to ingot recipe to avoid this conflict?

**Comment by pablocnvs** [comment]
That is getting fixed, it isn't the first time we get that suggestion
#371

**Comment by DStrand1** [comment]
Fixed as of PR #373

**Comment by Pnc6lx** [comment]
another conflict
V2O5+Al→V+Al2O3
also use Al dust

**Comment by Pnc6lx** [comment]
galena+O2→（4Ag and Pb nugget) or (PbO+6 Pb nugget+SO2)

**Comment by pablocnvs** [comment]
First one is fixed, same pr, and the second one is voltage tiered, so higher voltage should give you the better option

**Comment by Pnc6lx** [comment]
> First one is fixed, same pr, and the second one is voltage tiered, so higher voltage should give you the better option

I use 0.25 and find two recipe dust Al →ingot Al. maybe gtce recipe was not currect removed

**Comment by TechLord22** [comment]
The Aluminium dust duplicate will be fixed in chem fixes.

**Comment by Pnc6lx** [comment]
another conflict Concrete and Calcium Carbonate Solution
![image](https://user-images.githubusercontent.com/49830847/113528357-ea45cf80-95f2-11eb-9564-8110a53f5ce5.png)
![image](https://user-images.githubusercontent.com/49830847/113528370-f29e0a80-95f2-11eb-9a87-b42f3d1f9f25.png)
is it already fixed?

**Comment by Pnc6lx** [comment]
in last 0.22, still hvae Concrete and Calcium Carbonate Solution conflict

**Comment by TechLord22** [comment]
Fixing the Calcium Carbonate Solution in the latest commit of #388.

**Comment by Pnc6lx** [comment]
this two Concrete recipe still have conflict, they both use clay dust and stone dust

**Comment by TechLord22** [comment]
Both are now also fixed.

**Comment by Pnc6lx** [comment]
after the chem fix pr, AgCl cant be obtained. its used in AgBF4 of some ZPM+ recipe. it was get form Au chain

**Comment by ALongStringOfNumbers** [comment]
According to @DStrand1 The recipe for AgCl has been fixed and it should be obtainable now. Please open a new issue if you spot any more recipe conflicts.
