### ISSUE TITLE
Problems with Dev Environment using OpenJDK

### ISSUE THREAD

**Issue by DStrand1** [Gregicality/gregicality#396]
The classes `MetaTileEntityMonitorScreen` and `MetaTileEntityCentralMonitor` use the data structure `Pair<K, V>` from `javafx.util`, which is not bundled with the Java OpenJDK 8. I think that once PR #377 is merged, we should transition these classes to be using that data structure over the `javafx` structure for compatibility with OpenJDK.

**Comment by huneau** [comment]
ah yes, I dont see it 👍
