### ISSUE TITLE
Disassembler gives wrong tier of circuits from LV-EV machines

### ISSUE THREAD

**Issue by spooky-sooshi** [Gregicality/gregicality#401]
Disassembling specific machines from LV-EV gives IV, LuV, and HV (from EV machines) circuits. 
Some examples [here](https://imgur.com/a/pe9yreF).

Using Gregicality-1.12.2-0.21.5

**Comment by DStrand1** [comment]
Are you playing in skyblock? If not, what is your modlist?

**Comment by spooky-sooshi** [comment]
Playing in a custom pack. Here is the [modlist](https://pastebin.com/KQfxmNXQ). Really sorry for the trouble.

**Comment by DStrand1** [comment]
I haven't been able to test it yet, but I am going to call this an issue with Unidict, as they cause very unexpected behavior with GT often. Try removing that mod and see if the issue is still present

**Comment by DStrand1** [comment]
Closing this as it is an unfixable issue with Unidict
