### ISSUE TITLE
GTCE Rendering Changes

### ISSUE THREAD

**Issue by DStrand1** [Gregicality/gregicality#411]
In the PR to GTCE https://github.com/GregTechCE/GregTech/pull/1531, there were some changes to the rendering that will break some of our coremods. Changed files:

- `MetaTileEntityHolder#hasFastRenderer()` method was deleted, we were injecting code into this.
- `MetaTileEntityTESR#render()` now contains this code, so it may need to be added here instead.

I am posting this pre-emptively to get ahead of the issue, though this code could change further before it is merged. I would fix this if I were confident knowing what the coremod is doing, but I am not, so I assigned Kila since he is the one who wrote this section of code.

**Comment by Yefancy** [comment]
yeah, thank you. that's really something to note.
