### ISSUE TITLE
[Issue] TFC salt(ocean) water change texture when gregicality installed

### ISSUE THREAD

**Issue by SpeeeDCraft** [Gregicality/gregicality#421]
TerraFirmaCraft salt(ocean) water with Gregtech+Gregicality:
![2021-03-23_14 15 25](https://user-images.githubusercontent.com/52341158/112114619-d9588f80-8bea-11eb-8118-431d5d9e2c55.png)
TerraFirmaCraft without Gregtech+Gregicality:
![2021-03-23_14 19 23](https://user-images.githubusercontent.com/52341158/112114899-2ccadd80-8beb-11eb-9a9c-aca3e4dbeebf.png)

**Comment by hjae78** [comment]
I've had a look at this and [here](https://github.com/Gregicality/gregicality/blob/master/src/main/java/gregicadditions/fluid/GAMetaFluids.java#L51) is where we register our fluids. I don't understand why we would be overriding this fluid. Is the fluid called "sea_water"?

**Comment by idcppl** [comment]
https://www.curseforge.com/minecraft/mc-mods/uniq There this unique mod that can fix that, and are you sure it's not just an issue with GTCE. Cause the modpage for this also has a link to this issue, https://github.com/GregTechCE/GregTech/issues/1166

**Comment by SpeeeDCraft** [comment]
> I've had a look at this and [here](https://github.com/Gregicality/gregicality/blob/master/src/main/java/gregicadditions/fluid/GAMetaFluids.java#L51) is where we register our fluids. I don't understand why we would be overriding this fluid. Is the fluid called "sea_water"?

No, it's salt_water

**Comment by hjae78** [comment]
This is a GTCE issue then
