### ISSUE TITLE
[Suggestion] Add support GT: Remastered?

### ISSUE THREAD

**Issue by KevinChang0916** [Gregicality/gregicality#428]
Title.

**Comment by brachy84** [comment]
That would require rewriting a lot of code, so not gonna happen most likely.

**Comment by KevinChang0916** [comment]
okay.

**Comment by hjae78** [comment]
What features does GT: Remastered have that we don't have?

**Comment by brachy84** [comment]
oh wait, there isn't actually much gtr has that we don't have. The only thing is see is ic2 eu/rf support. (I assume the cables can directly connect to rf handlers)

**Comment by tekcay** [comment]
and item pipes

**Comment by KevinChang0916** [comment]
Or you can add IC2 EU/RF/FE compatibility, and need wrench to break machine, and add heat exchanger..?
If can, there is no need to add GTR compatibility

**Comment by DStrand1** [comment]
We have blocks that can convert from/to RF similar to the CEU mod. IC2 power I do not believe is planned. The heat exchanger is planned, and the wrench to break machine probably will not happen either, at least not in Gregicality.

**Comment by KevinChang0916** [comment]
ok

**Comment by hjae78** [comment]
I'll close this since we already have an open suggestion for item pipes
