### ISSUE TITLE
add different kinds of ore density

### ISSUE THREAD

**Issue by huneau** [Gregicality/gregicality#45]

**Comment by hjae78** [comment]
What were the different types and multipliers you were thinking? I know you talked about it on discord at some point

**Comment by huneau** [comment]
Maybe x1|x2|x4|x8
and add conf as always

**Comment by hjae78** [comment]
What about small ore like gt5?

**Comment by huneau** [comment]
not a huge fan of

**Comment by Shattered2909** [comment]
Poor = 0.25
Small = 0.5
(Normal)
Rich = 1.5
Dense = 2.0
