### ISSUE TITLE
recipe conflict - Phosphorus Chloride and  Phosphorus Trichloride

### ISSUE THREAD

**Issue by nanmumc** [Gregicality/gregicality#472]
![image](https://user-images.githubusercontent.com/25528572/116787897-5d027780-aad9-11eb-96a8-37a361c84e0d.png)
![image](https://user-images.githubusercontent.com/25528572/116787901-61c72b80-aad9-11eb-97e0-d0e83ba1c9dc.png)

It makes it impossible for me to process nuclear depleted fuel to get radon.
So it prevents me from getting PU-244 and reaching ZPM level.

suggestion:
add Programmed Circuit for Phosphorus Chloride.

**Comment by TechLord22** [comment]
This has been fixed in the latest version on github in either #388 or #460. One of those fluids will also be removed entirely. The next release will contain many recipe conflict fixes and chemistry corrections. I'll close this for now.
