### ISSUE TITLE
Missing Textures as of 0.22.2

### ISSUE THREAD

**Issue by DStrand1** [Gregicality/gregicality#490]
Remaining missing textures as of the latest release, and our development progress (shown with volunteers to create them, if we have them):

- [x] Rotating Transparent Surface
- [ ] Ballast: Mothmoss
- [x] Magnetic Trap: Regian
- [ ] Laser Cooling Unit
- [x] Laser Diode
- [x] Quantumchromodynamic Protecting Plating: Tech22

**Comment by TechLord22** [comment]
Plating Texture: 
![plate](https://user-images.githubusercontent.com/37029404/118588156-dce04100-b76b-11eb-81e1-88606dda8e49.png)

Mcmeta:
```
{
    "animation": {
        "interpolate": true,
        "frametime": 10,
        "frames":[0,1,2,3,4,5,6,7,8,9,10,11]
    }
}

**Comment by TechLord22** [comment]
Laser Diode texture by "max is the spy" on discord. Original image based off of Regian's (on discord) design.
![laserdiode_1](https://user-images.githubusercontent.com/37029404/119721448-29e1a880-be39-11eb-8c9c-5666195108c0.png)

**Comment by Regian24** [comment]
Magnetic Trap

![magnetictrap](https://user-images.githubusercontent.com/64612588/119725123-da6a9f00-be6f-11eb-8bf6-630555a5b274.png)
😳

**Comment by Xalendro** [comment]
Rotating Transparent Surface
![rotating_transparent_surface_0](https://user-images.githubusercontent.com/28224717/120084462-08065100-c0d9-11eb-9206-c88224376bda.png)
![rotating_transparent_surface_1](https://user-images.githubusercontent.com/28224717/120084463-089ee780-c0d9-11eb-8578-1c326c6e57cc.png)
![rotating_transparent_surface_2](https://user-images.githubusercontent.com/28224717/120084464-09377e00-c0d9-11eb-965c-610d5333e100.png)
![rotating_transparent_surface_3](https://user-images.githubusercontent.com/28224717/120084465-09d01480-c0d9-11eb-8b79-9d866dc1b3a7.png)
![rotating_transparent_surface_4](https://user-images.githubusercontent.com/28224717/120084466-09d01480-c0d9-11eb-99dd-8b29b4c0ec28.png)
![rotating_transparent_surface_5](https://user-images.githubusercontent.com/28224717/120084469-0a68ab00-c0d9-11eb-8ccd-2ea38a8fff92.png)

**Comment by Xalendro** [comment]
Laser Cooling Unit
![laser_cooling_unit](https://user-images.githubusercontent.com/28224717/120096200-bdb1be00-c132-11eb-80af-da4fc8d978d8.png)

**Comment by Xalendro** [comment]
Laser Cooling Unit
![lcu](https://user-images.githubusercontent.com/28224717/121767271-e2109000-cb5f-11eb-8950-e2761f65bf0b.png)

**Comment by ALongStringOfNumbers** [comment]
I am closing this issue in favor of #568. All the textures in this issue have been incorporated into the game or existing PRs, except for the Rotating Transparent Surface, for which there needs to be a mcmeta file.
