### ISSUE TITLE
Infinite calcium loop from Organic Fertilizer

### ISSUE THREAD

**Issue by Charnuz** [Gregicality/gregicality#491]
The recipe for crafting the fertilizer takes 2 less calcium than what you get back from the electrolyzer.

https://github.com/Gregicality/gregicality/blob/3c239958427b65eb53f296f6e2d02c64c55ba8be/src/main/java/gregicadditions/GAMaterials.java#L319

https://github.com/Gregicality/gregicality/blob/3c239958427b65eb53f296f6e2d02c64c55ba8be/src/main/java/gregicadditions/recipes/chain/VariousChains.java#L222-L228

**Comment by DStrand1** [comment]
This is definitely an issue, but I think since fertilizer is important, and is already an arbitrary chemical formula, I would rather disable its electrolysis than nerf its creation recipe. Thanks for reporting this issue
