### ISSUE TITLE
[BUG] Electric Implosion Compressor has no Recipes

### ISSUE THREAD

**Issue by DStrand1** [Gregicality/gregicality#498]
As a result of changes to the recipe property system in https://github.com/GregTechCE/GregTech/pull/1580, the Implosion Compressor no longer has explosives stored as a recipe property. As a result, the Electric Implosion Compressor recipe generation will always fail. This issue should be resolved by the solution to https://github.com/GregTechCE/GregTech/issues/1614

**Comment by alfuken** [comment]
Any ETA on fix? If not, what's the latest GTCE version that works without causing this issue so I can rollback GTCE?..
