### ISSUE TITLE
A crash report

### ISSUE THREAD

**Issue by mxancl** [Gregicality/gregicality#500]
Like the title，I get a crash while I use this mod. This is the crash report, hope you can fix the bug or tell me why it happened thx.
https://paste.dimdev.org/epequsemek.mccrash this is the website that Minecraft suggest me to give to you.

**Comment by DStrand1** [comment]
Looks like you are out of ID's for Items in the game. Either try to remove a few mods to free up IDs, or install the mod [JustEnoughIDs](https://www.curseforge.com/minecraft/mc-mods/jeid).

I would like to add that while GTCE and Gregicality appear to add a massive number of items, we do it in a way that saves on IDs. We may only combined add a total of 50 actual Items with unique IDs. Many mods other than us will have many more

**Comment by mxancl** [comment]
Thank you very much.
