### ISSUE TITLE
Missing seed oil recipes

### ISSUE THREAD

**Issue by tomasbrod** [Gregicality/gregicality#501]
After installing gregicality (v0.22.2 and v0.22.3.2) seed oil recipes are missing for Seeds, Melon seeds and Pumpkin seeds. recipe with Beetroot seeds remains. Setting `B:GenerateExtractorRecipes=false` works around the bug. I believe this is issue on the following lines:

https://github.com/Gregicality/gregicality/blob/ee2952e029d93c8d3eb770c1973637b926b2ba16/src/main/java/gregicadditions/integrations/bees/ForestryCommonProxy.java#L100-L101

https://github.com/Gregicality/gregicality/blob/3c239958427b65eb53f296f6e2d02c64c55ba8be/src/main/java/gregicadditions/integrations/bees/ForestryCommonProxy.java#L113-L115

Could it work if those were in reverse order?

**Comment by DStrand1** [comment]
Thank you for reporting this. This could actually be the fix we need for Seed Oil, which has a few problems with mods like Forestry and Thermal Expansion. Thanks for reporting this and suggesting a possible fix
