### ISSUE TITLE
Chemical Reactor losing output

### ISSUE THREAD

**Issue by HoshinoTented** [Gregicality/gregicality#504]
Chemical Reactor still creating and losing something even the output slots don't have enough space.

Firstly, I was creating some Rubber: 
![image](https://user-images.githubusercontent.com/25280943/119321523-523d9b80-bcaf-11eb-9deb-eeed1e3c9d33.png)

Then I was trying to creating some Naphtha without cleaning the output slots:
![image](https://user-images.githubusercontent.com/25280943/119321690-8022e000-bcaf-11eb-9966-fc5370379d98.png)

The machine started working, and then lost some output:
![image](https://user-images.githubusercontent.com/25280943/119321757-9335b000-bcaf-11eb-8151-61cd6648a4d0.png)
![image](https://user-images.githubusercontent.com/25280943/119321774-96c93700-bcaf-11eb-9fe4-890123e09fc0.png)

Is it gregicality's problem? I am using GregicalitySkyblockEdition 5.2.

**Comment by DStrand1** [comment]
I believe this is a rare bug with GTCE that can cause exactly 1 recipe to go through despite there not being the proper space for the outputs. Had you tried to make two batches of Naphtha, the second wouldn't go through because only then it would fail the outputs check.

**Comment by HoshinoTented** [comment]
got it
