### ISSUE TITLE
Exotic Circuit Textures

### ISSUE THREAD

**Issue by Regian24** [Gregicality/gregicality#518]
- [x] Untreated Exotic Wafer
- [x] Cryogenic Interface:
either this https://media.discordapp.net/attachments/848652937580511282/850019307568234506/cryogenicinterface.png (Regian), this, (https://media.discordapp.net/attachments/848652937580511282/850022045043392532/Screen_Shot_2021-06-03_at_10.43.56_AM.png) (mothmoss), or also this one, we need to choose 
https://cdn.discordapp.com/attachments/848652937580511282/850283048384725002/Cryo_unit.png
 (max is the spy)
- [x] Excitation Maintainer
- [x] Exotic Wafer https://media.discordapp.net/attachments/848652937580511282/850284385248215060/exoticchip.png(Regian)
- [x] Exotic Chip 
- [x] Fullerene Polymer Matrix Covered PEEK Semisolid Tubing 
(https://media.discordapp.net/attachments/848652937580511282/850127333343494144/fine_tubing_idk.png) (Regian)
- [x] Fullerene Polymer Matrix Fine Tubing
- [x] X-Ray Waveguide 
- [x] Microfocus X-Ray Tube (https://cdn.discordapp.com/attachments/848652937580511282/850263059625017354/aaaaa.png) (trerri)
- [x] X-Ray Mirror Plate (https://cdn.discordapp.com/attachments/848652937580511282/850278799722414100/Xray_mirror.png)(max is the spy)
- [x] X-Ray Laser 
(https://media.discordapp.net/attachments/848652937580511282/850278828802703360/New_Piskel_2.png) (Max is the spy)
- [x] Rydberg Spinorial Assembly https://media.discordapp.net/attachments/848652937580511282/849755377276682240/unknown.png (trerri)
- [x] Exotic Processing Core (https://cdn.discordapp.com/attachments/848652937580511282/849749210529660978/exoticprocessingcore.png) (Regian)

**The current Bioware Circuits and SMD textures will be moved up to Exotic. So we need to change the texture for the Bioware circuits. Color should be dark green**
- [x] Bioware Processor
- [x] Bioware Assembly
- [x] Bioware Computer
- [x] Bioware Mainframe
- [x] Bioware SMD Diode
- [x] Bioware SMD Transistor
- [x] Bioware SMD Resistor
- [x] Bioware SMD Capacitor

**Comment by hjae78** [comment]
Could you update the links to point to the image directly rather than the message?

**Comment by MaxistheSpy** [comment]
![image](https://user-images.githubusercontent.com/85330647/120765471-19cb6800-c4ce-11eb-88a5-64cc9c681aa2.png)
![image](https://user-images.githubusercontent.com/85330647/120765497-20f27600-c4ce-11eb-85e9-2576c6a0a421.png)
Heres a basic laser and mirror plate design I made(they are currently linked in discord aswell). The laser is fine and a retextured version of the lasor diode design that may or may not have gotten included somewhere. The mirror plate could use work and I would be glad to do so but if the current design is fine I will keep that
![Xray plate alt 2](https://user-images.githubusercontent.com/85330647/120766518-29977c00-c4cf-11eb-909b-0f867f416c87.png)
Heres an alt design for the mirror too

**Comment by MaxistheSpy** [comment]
Im pretty sure we are all just going on guesswork and creative license if anyone with physics knowledge or who knows what these things are/do cares to give an explanation of what they look like/might look like or some physical reference that would be helpful but not needed.

**Comment by MaxistheSpy** [comment]
Wave guide 
![image](https://user-images.githubusercontent.com/85330647/120773349-1f2cb080-c4d6-11eb-85b4-1879201ce3b6.png)
![image](https://user-images.githubusercontent.com/85330647/120773393-2784eb80-c4d6-11eb-9226-3b439e08a594.png)

**Comment by TechLord22** [comment]
Green Bioware Circuit Textures
![bioware_mainframe](https://user-images.githubusercontent.com/37029404/120902491-bdbc2d00-c60e-11eb-96c7-465146a446d0.png)
![bioware_computer](https://user-images.githubusercontent.com/37029404/120902492-bdbc2d00-c60e-11eb-9f4a-bca62393be05.png)
![bioware_processor](https://user-images.githubusercontent.com/37029404/120902493-bdbc2d00-c60e-11eb-9195-ae23a53e39ac.png)
![bioware_assembly](https://user-images.githubusercontent.com/37029404/120902494-bdbc2d00-c60e-11eb-9ec3-a35854d4abde.png)

**Comment by Regian24** [comment]
![excitation maintainer](https://user-images.githubusercontent.com/64612588/120925497-325b9e00-c6d9-11eb-94c4-0c97f2a3080c.png)

{
    "animation": {
        "frametime": 3,
        "frames": [
            0, 1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1, 0]
    }
}

**Comment by MaxistheSpy** [comment]
> ![excitation maintainer](https://user-images.githubusercontent.com/64612588/120925497-325b9e00-c6d9-11eb-94c4-0c97f2a3080c.png)
> 
> {
> "animation": {
> "frametime": 3,
> "frames": [
> 0, 1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1, 0]
> }
> }

![excitation_maintainer (4)](https://user-images.githubusercontent.com/85330647/120933610-bef16680-c6af-11eb-9b02-bfc1b9e38999.png)
I shaded this and made it greyscale tech said I should put it here.
![excitation_maintainer-1 png (3)](https://user-images.githubusercontent.com/85330647/120933629-cfa1dc80-c6af-11eb-993f-efd0b421e18c.png)

**Comment by MaxistheSpy** [comment]
> * [ ]  Untreated Exotic Wafer
> * [x]  Cryogenic Interface:
>   either this https://media.discordapp.net/attachments/848652937580511282/850019307568234506/cryogenicinterface.png (Regian), this, (https://media.discordapp.net/attachments/848652937580511282/850022045043392532/Screen_Shot_2021-06-03_at_10.43.56_AM.png) (mothmoss), or also this one, we need to choose
>   https://cdn.discordapp.com/attachments/848652937580511282/850283048384725002/Cryo_unit.png
>   (max is the spy)
> * [x]  Excitation Maintainer
> * [x]  Exotic Wafer https://media.discordapp.net/attachments/848652937580511282/850284385248215060/exoticchip.png(Regian)
> * [ ]  Exotic Chip
> * [x]  Fullerene Polymer Matrix Covered PEEK Semisolid Tubing
>   (https://media.discordapp.net/attachments/848652937580511282/850127333343494144/fine_tubing_idk.png) (Regian)
> * [ ]  Fullerene Polymer Matrix Fine Tubing
> * [x]  X-Ray Waveguide
> * [x]  Microfocus X-Ray Tube (https://cdn.discordapp.com/attachments/848652937580511282/850263059625017354/aaaaa.png) (trerri)
> * [x]  X-Ray Mirror Plate (https://cdn.discordapp.com/attachments/848652937580511282/850278799722414100/Xray_mirror.png)(max is the spy)
> * [x]  X-Ray Laser
>   (https://media.discordapp.net/attachments/848652937580511282/850278828802703360/New_Piskel_2.png) (Max is the spy)
> * [x]  Rydberg Spinorial Assembly https://media.discordapp.net/attachments/848652937580511282/849755377276682240/unknown.png (trerri)
> * [x]  Exotic Processing Core (https://cdn.discordapp.com/attachments/848652937580511282/849749210529660978/exoticprocessingcore.png) (Regian)
> 
> **The current Bioware Circuits and SMD textures will be moved up to Exotic. So we need to change the texture for the Bioware circuits. Color should be dark green**
> 
> * [x]  Bioware Processor
> * [x]  Bioware Assembly
> * [x]  Bioware Computer
> * [x]  Bioware Mainframe
> * [ ]  Bioware SMD Diode
> * [ ]  Bioware SMD Transistor
> * [ ]  Bioware SMD Resistor
> * [ ]  Bioware SMD Capacitor
The exotic wafer listed here is actualy the untreated exotic wafer the treated one is below credit to (regian & Tech)
![Treated Exotic wafer](https://user-images.githubusercontent.com/85330647/121122252-f4906f80-c7d5-11eb-8362-82d0eb3e9693.png)

**Comment by MaxistheSpy** [comment]
![image (9)](https://user-images.githubusercontent.com/85330647/121127517-bcd9f580-c7de-11eb-9c32-177eed0c0a18.png)
![Graphine tube (1) (1)](https://user-images.githubusercontent.com/85330647/121127519-be0b2280-c7de-11eb-816f-bc5c9b16c3b4.png)
Ideas for the fulerine matrix fine tubing

**Comment by MaxistheSpy** [comment]
![component smd transistor (3)](https://user-images.githubusercontent.com/85330647/121132909-9455f980-c7e6-11eb-9bd3-2e0392718c99.png)
![component smd transistor (2)](https://user-images.githubusercontent.com/85330647/121132912-94ee9000-c7e6-11eb-96be-616f432da545.png)
![component smd transistor (1)](https://user-images.githubusercontent.com/85330647/121132914-94ee9000-c7e6-11eb-9f4d-0eaba32c8d8f.png)
![component smd capacitor (1)](https://user-images.githubusercontent.com/85330647/121132917-94ee9000-c7e6-11eb-854e-89d9f1c4485f.png)
Heres some flat versions of the SMD components. the green lacks a gradient but I figured I would post them anyway

**Comment by ReclipseTheOne** [comment]
A retexture of the X-Ray Laser if anybody needs:
![X-Ray Laser](https://user-images.githubusercontent.com/17797013/124902382-89f86c80-dfeb-11eb-9290-e590eb20f361.png)

**Comment by pablocnvs** [comment]
And the exotic chip that hasn't seen much objection
![exotic chip](https://user-images.githubusercontent.com/64352555/124902576-574a7600-dfe3-11eb-8642-55d755102a7c.png)
