### ISSUE TITLE
Wrong Texture: Fused Quartz

### ISSUE THREAD

**Issue by HoshinoTented** [Gregicality/gregicality#527]
![image](https://user-images.githubusercontent.com/25280943/121281731-f740b100-c90a-11eb-9d95-23d007fc4fe1.png)

**Comment by HoshinoTented** [comment]
Using Gregicality Skyblock Edition 5.2

**Comment by HoshinoTented** [comment]
or Gregicality 1.12.2-0.22.2

**Comment by hjae78** [comment]
This isn't a Gregicality issue, this issue belongs in the Skyblock Edition github
