### ISSUE TITLE
The large multi use switching mode does not work, it has always been the compressor mode

### ISSUE THREAD

**Issue by yang-fu** [Gregicality/gregicality#532]
The large multi use switching mode does not work, it has always been the compressor mode

It is now in lathe mode
![捕获](https://user-images.githubusercontent.com/66714394/121779428-28043d00-cbce-11eb-8384-b397c23bf1da.PNG)
I put in a Sn
![捕获1](https://user-images.githubusercontent.com/66714394/121779485-731e5000-cbce-11eb-99d0-0604c7472d4c.PNG)
Machine not working
Then I put in a set of metal ingots
![捕获2](https://user-images.githubusercontent.com/66714394/121779523-b5479180-cbce-11eb-97d1-4c3f4df2513a.PNG)
It becomes this

**Comment by hjae78** [comment]
This will be fixed in an upcoming release
