### ISSUE TITLE
Missing neutral matter and positive matter recipes

### ISSUE THREAD

**Issue by shanzhaikabi** [Gregicality/gregicality#543]
In version v0.22.2, there's no recipes of neutral matter and positive matter, except by Neutral/Positive Matter Comb. So there's no way to breed neutral matter bee and positive matter bee, while uu-matter bee is not available either.

**Comment by hjae78** [comment]
UU-Matter has a new recipe

**Comment by shanzhaikabi** [comment]
> UU-Matter has a new recipe

But UU-Matter BEE still needs neutral/positive matter bee, and they are not available.

**Comment by pablocnvs** [comment]
We can always change those bees to be fermionic and bosonic bees, which IIRC gives you UU-matter
