### ISSUE TITLE
0.21.0 update Cosmic tier and UHV+ power

### ISSUE THREAD

**Issue by huneau** [Gregicality/gregicality#56]
Cosmic Tier Circuit and UHV+ Power

A `qbit Computer` consume 1 UV EU and 1 `UHV Circuit` to produce 1 qbit in `The Optical Fiber` network
`The Optical Fiber` can support up to 16x `qbit Computer`
A `qbit Generator` can convert 1 qbit to 1UHV EU
A `qbit Generator` can provide up to 16UHV

`Cosmic dust` can be Collect into a `Cosmic Collector` @slow rate or can be crafted by mixing `Neutronium` + `Mendelevium` + <rarest chemical>
`Cosmic ingot` can be smelt into a blast furnace in a new Coil Tier

UEV Casing use Cosmic Ingot and new plastic chemical
New Cosmic circuit 

![image](https://user-images.githubusercontent.com/9199240/84709529-9d5d1380-af62-11ea-87a5-7ec570860011.png)

**Comment by hjae78** [comment]
Can you elaborate how this would work? Would a qbit be an item or some sort of data structure? Then this 1 qbit becomes 1 amp UHV? Isn't that a little too much free energy? And expensive in terms of circuits?

**Comment by hjae78** [comment]
Also is this what you meant by the quantum computer?

**Comment by hjae78** [comment]
Also maybe MK IV fusion for this tier? Either taking cosmic components or making a material used for cosmic.

**Comment by Shattered2909** [comment]
I am not sure if I like this, it seems very simple and straightforward. Sure, I love the idea of adding UHV but this is not complex.

**Comment by hjae78** [comment]
> I am not sure if I like this, it seems very simple and straightforward. Sure, I love the idea of adding UHV but this is not complex.

I'd love to hear any ideas you have about it. This hasn't been started on at all so plenty of time to brainstorm

**Comment by Zalgo239** [comment]
I have an idea to make something similar that makes a little more sense

Using some sort of complicated transformer multiblock
Something that needs to be built with superconductors, requiring liquid helium or liquid nitrogen to operate. Maybe even have the body of the multiblock filled with some type of oil or other insulation to avoid arcs.
If you want the "three lines go into one" you can keep basically the same layout for the UV -> UHV process, just replace the three Qbits with three different phases of alternating current
https://en.wikipedia.org/wiki/Three-phase_electric_power
IRL to know everything about a power system you need the operating Voltages, Currents, Frequencies, and Phases. If you know that two wires are kept at the same voltage and frequency but forget that they have different phases and you connect them you will short the power lines. In game this could lead to a transformer explosion.

**Comment by hjae78** [comment]
Materials for UHV/UEV: Trinium, Adamantium, Vibranium

**Comment by huneau** [comment]
glass fiber 
https://media.discordapp.net/attachments/701354865657643070/762775908745740308/Glass_fiber.png

**Comment by huneau** [comment]
https://cdn.discordapp.com/attachments/701354865657643070/762780412551757834/FiberOptics.png

**Comment by hjae78** [comment]
https://cdn.discordapp.com/attachments/701354865657643070/764425154494988288/DegenerateElectrons1.png

**Comment by Zalgo239** [comment]
Recipe proposal for those fusion reactor blocks

![Blankets](https://user-images.githubusercontent.com/67443118/98854972-95df5f00-245b-11eb-9f1d-2ca99d22f614.png)
