### ISSUE TITLE
Crash without mystical agriculture

### ISSUE THREAD

**Issue by hjae78** [Gregicality/gregicality#57]
https://cdn.discordapp.com/attachments/704380911206006855/722354843762688025/crash-2020-06-16_09.29.51-client.txt

I'm guessing it has to do with the CT method to add crops but not sure why or how. Tried building a fix wrapping the entire method in a check for if mystical aggraditions was loaded but didn't help.

**Comment by Pival81** [comment]
I'm experiencing this crash with the latest version compiled from source, even after disabling the mystical agriculture compat in the configs.
