### ISSUE TITLE
Issues related to multiblock machine when maintenance is disabled

### ISSUE THREAD

**Issue by Quaerere-Git** [Gregicality/gregicality#589]
Version:0.23-RC
When right-clicking multiblock controller with free wrench, the game crashes. Also, the structure of multiblock machine is not displayed in JEI page.
However, everything works fine when maintaince is enabled.
[crash-2021-08-15_16.29.38-client.txt](https://github.com/Gregicality/gregicality/files/6988133/crash-2021-08-15_16.29.38-client.txt)
the crash report
![2021-08-15_20 48 58](https://user-images.githubusercontent.com/42565872/129479192-fd087512-bbac-4638-ae6c-c0fad1522596.png)
the structure page is missing

**Comment by TechLord22** [comment]
I'm trying to replicate this in #580. I can't reproduce this with maintenance on or off. For the JEI preview, your version of the multi pr beta might be outdated, as that is present for me. For the freedom wrench, I was not able to reproduce the crash with any of the freedom wrench's modes in every possible configuration of the controller. 

If you could provide more detailed steps for reproducing this bug, it would be much appreciated. If you want a newer version of the multi pr, with many fixes already added, please search for it on our discord or ping me directly there.

**Comment by Quaerere-Git** [comment]
I tested in the latest version and everything works fine.
Thank you :)
