### ISSUE TITLE
Multiblocks void outputs

### ISSUE THREAD

**Issue by hjae78** [Gregicality/gregicality#6]
User in discord reported that Large Mixer and Large Sifter voided outputs. Will update as I try to replicate.

**Comment by hjae78** [comment]
Reproduced with Large Sifter, UV energy input, EV item input/output, platinum salt recipe. Full stack in, nothing out.

**Comment by hjae78** [comment]
Same setup with purified cinnabar ore produced no chipped cinnabar or purified piles of cinnabar dust.

**Comment by hjae78** [comment]
Results from Large Centrifuge seem incorrect, EV item input/output, UV energy input, doing the Sticky Comb recipe. 10 stacks of combs resulted in 436 Rubber and 22 Beeswax. Recipe is 30% + 10%/tier for beeswax, 70% + 10%/tier for Rubber.

**Comment by hjae78** [comment]
No luck reproducing the issue with Large Mixer and Grisium dust as reported in discord.

**Comment by hjae78** [comment]
Not sure if we should close for now or keep open... Was reported that Large Mixer voided output as well so maybe some other bug as well?

**Comment by huneau** [comment]
im a bit afraid of that 🤔
