### ISSUE TITLE
Incompatibility between Shadows of Greg and Gregicality mods

### ISSUE THREAD

**Issue by NorthHusky** [Gregicality/gregicality#659]
When using mods Gregicality and Shadows of Greg gave an error about Mod ID

![image](https://user-images.githubusercontent.com/105886827/171682430-b8086b4e-3104-43dc-9a25-71e189f1998c.png)

MC: 1.12.2
Forge: 14.23.5.2860
Shadows_of_Greg-1.12.2-2.20.2
Gregicality-1.12.2-0.24.0-final
gregtech-1.12.2-1.17.1.770

**Comment by htmlcsjs** [comment]
gregicality is a fork of sog

**Comment by ALongStringOfNumbers** [comment]
As stated above, Gregicality is a fork of SoG, and the fork was made without changing the mod id, so the two mods are incompatible with each other.

However, Gregicality adds most of the content that SoG adds, as well as a bunch more stuff, so there is no real reason to use SoG if you are using Gregicality.
