### ISSUE TITLE
conflict blast alloy furnace

### ISSUE THREAD

**Issue by huneau** [Gregicality/gregicality#69]
Another conflict, blast alloy furnace always crafts kanthal, not incoloy ma-956, ignoring circuit config in different inputs

**Comment by hjae78** [comment]
Can't replicate. Put Incoloy inputs in a hatch with circuit 4, have another hatch with circuit 3. Results in incoloy. Yes, if you only have circuit 3 in any hatch it will craft kanthal and not incoloy but this is expected behaviour.

**Comment by huneau** [comment]
fix in 96309eddefb10d4aa0c9ec25fe919208ba89dc91
