### ISSUE TITLE
GTCE Seed Oil unobtainable

### ISSUE THREAD

**Issue by hjae78** [Gregicality/gregicality#76]
~~Reported that putting gregtech then thermal foundation in GTCE's mod priorities would make only Thermal Foundation's seed oil obtainable but some recipes still required the Forestry variant. Unsure if we have anything to do with it but he said it worked when he only had SoG.~~

**Comment by hjae78** [comment]
Correction; GTCE seed oil is obtainable from Forestry cherries but recipes require Thermal Foundation oil.

**Comment by huneau** [comment]
gtce seed oil is remove if forestry seed oil already exist
