### ISSUE TITLE
Server crash on startup after updating to 0.20.1/2

### ISSUE THREAD

**Issue by aking4125** [Gregicality/gregicality#80]
Hello, Currently getting a server crash upon updating to Gregicality 0.20.1 or 0.20.2.

0.19.8 works perfectly fine. Attached is the crash report and latest.log. If there's any additional information needed. Please let me know. Clients load Gregicality 0.20.2 perfectly fine. Possibly an issue on the world itself? My apologizes if this issue was already reported.

[crash-2020-06-23_04.44.58-server.txt](https://github.com/Gregicality/gregicality/files/4818239/crash-2020-06-23_04.44.58-server.txt)
[latest.log](https://github.com/Gregicality/gregicality/files/4818241/latest.log)

**Comment by hjae78** [comment]
Thank you for reporting this, it's a very strange issue to me. Just to make sure can you update GTCE to the latest version? I am 99.9% that won't change anything but just in case

**Comment by hjae78** [comment]
You're using Forge 14.23.5.2854, downgrade to 14.23.5.2847. GTCE isn't compatible with 14.23.5.2854. Let me know if this fixes it.

**Comment by aking4125** [comment]
Wow. Not entirely sure how we missed the 507 update to GTCE. The file was downloaded on June 9th according to Windows yet Curseforge reads June 6th. Oh well, I blame myself for that.

I'm attempting the update on the server now, gonna be a bit before it loads up. I'm still not sure why the client works with Gregicality 0.20.1/2 but the server doesn't.

As for Forge. I'll attempt the downgrade but due note Forge 2854 is listed as a Recommended download on the Forge site so we just nab'd that. I am ready with the downgrade if anything however.

**Comment by hjae78** [comment]
GTCE has a lot of issue with Forge 2847, there are a ton of issue on their GitHub which require downgrading to 2847

**Comment by aking4125** [comment]
Welp. Updated GTCE to 507 and Gregicality to 0.20.2 still crashes with the same result. Regardless if it's Forge 2847 or 2854.


[crash-2020-06-23_07.42.33-server.txt](https://github.com/Gregicality/gregicality/files/4819095/crash-2020-06-23_07.42.33-server.txt)

**Comment by hjae78** [comment]
Ah, I see the issue now. Pushed to PR

**Comment by aking4125** [comment]
Hopefully it didn't cause anything too serious. Unknown if it's just the server configuration on our end, the world or something else.

**Comment by hjae78** [comment]
No, decal just forgot to make a method only client sided, no big deal

**Comment by huneau** [comment]
fix in a0d36b44ed196fc5a3681776b007be2d51577e0c

**Comment by huneau** [comment]
wait and see in 0.20.3

**Comment by huneau** [comment]
@aking4125 can you tell me its working ?

**Comment by aking4125** [comment]
I'll let you know in about an hour when I can access the server machine.

**Comment by hjae78** [comment]
Great, no troubles at all!
