### ISSUE TITLE
Crash using CT but no Mystical Agriculture Mod

### ISSUE THREAD

**Issue by Kehaan** [Gregicality/gregicality#85]
Hey

So i wanted to try this mod, but seems like i am crashing using it. According to the CraftTweaker dev (which is a friend of mine) says, that it is because your mod is making CT ask/load Mystical Agriculture. But since i don't use that mod i crashes.

Crashlog:
[crash-2020-06-24_11.54.42-client.txt](https://github.com/Gregicality/gregicality/files/4825098/crash-2020-06-24_11.54.42-client.txt)

- Kehaan

**Comment by huneau** [comment]
I tested it this morning. Can you downgrade to 0.20.2 plz

**Comment by Kehaan** [comment]
Downgraded to 0.20.2, and that version works just fine.

So i guess something must have changed in the newer version.

**Comment by huneau** [comment]
missing `@ModOnly(MysticalAgradditions.MOD_ID)`
I deployed a fix with the same version

**Comment by huneau** [comment]
the new version is deploed
