### ISSUE TITLE
Endless loop making Basic Circuit

### ISSUE THREAD

**Issue by ChromaPIE** [Gregicality/gregicality#98]
###### Happens when all Bending Cylinder settings set to false

**Basic Circuit**, requiring **Resistors**, which need two **Fine Copper Wires** for each. Aside from recipes related to machines, Fine Copper Wires can only be made by Cutters cutting **Copper Foils** in the crafting grid. The problem is, Copper Foils only got one recipe, which is processed by the **Bending Machine**, a machine requiring Basic Circuits to be crafted, which leads players to the very beginning of this endless loop.

**Comment by hjae78** [comment]
I think this is only an issue when disabling the recipe for foils with bending cylinders but having fine wires from foils enabled.

**Comment by ChromaPIE** [comment]
But even though I set  fine wires from foils to false the recipe still exists

**Comment by hjae78** [comment]
Hmm this config option does nothing at all actually

**Comment by hjae78** [comment]
Ok pushed fix
